### ISSUE TITLE
Xfce 4.12 - Pulse audio button

### ISSUE THREAD

**Issue by agrafe** [vinceliuice/Qogir-theme#10]
Hi,
With the light version,  the pulse audio button seems to have a problem.

https://image.ibb.co/cWLkUe/Capture_d_cran_2018_09_02_18_12_38.png
https://image.ibb.co/bUqkUe/Capture_d_cran_2018_09_02_18_12_58.png

**Comment by vinceliuice** [comment]
Fixed now
