### ISSUE TITLE
Wrong Firefox maximize/ unmaximize button when maximized

### ISSUE THREAD

**Issue by lakrivit** [vinceliuice/Qogir-theme#100]
When I maximize my Firefox window using the squared theme variant the maximize/ unmaximize titlebar button doesn't change.

Normally when maximizing a window the `maximize` titlebar button gets replaced by the `restore window` button. I also notice the `minimize` button is slightly shifted to the left instead of being centered.

I've added the userChrome fix and set `widget.content.gtk-theme-override` to `Qogir-win-light`. My Firefox density is set to `compact`.

![firefox_slim_titlebar_buttons_maximized](https://user-images.githubusercontent.com/58817233/74642820-94eafc80-516b-11ea-8c76-a929288a32a6.png)

Is it also easily possible to change the width of the titlebar buttons? Would like to play around with that for personal use to mimick the vscode titlebar as in the picture below if possible.

![vscode_titlebar_buttons_maximized](https://user-images.githubusercontent.com/58817233/74643035-fc08b100-516b-11ea-9655-12cf9f7cd2ac.png)

**Comment by vinceliuice** [comment]
Don't worry I'll make a firefox theme for qogir, then this will not be a issue anymore

**Comment by lakrivit** [comment]
Thank you :) Love your Qogir theme and icon pack

**Comment by vinceliuice** [comment]
You are welcome!
