### ISSUE TITLE
Error message when installing in gnome shell 3.36

### ISSUE THREAD

**Issue by csteinforth** [vinceliuice/Qogir-theme#103]
When installing by ./install.sh -i I get the message 

`compound selectors may no longer be extended. Consider `@extend ${compound.components.join(', ')}` instead.`

Am I missing something here?

**Comment by closingin** [comment]
Hello @csteinforth 

You should downgrade your `libsass` package! An update got released recently, which deprecates a feature that this theme is using. But using version `3.6.1` will fix your problem! :slightly_smiling_face:

**Comment by csteinforth** [comment]
I can confirm that downgrading `libsass` to `3.6.1` works. Thanks @closingin !

**Comment by vinceliuice** [comment]
Fixed
