### ISSUE TITLE
Nautilus' Qogir Icon is Blurry on a 4k Display

### ISSUE THREAD

**Issue by HymanZHAN** [vinceliuice/Qogir-theme#104]
I see that the incorrect indentation mentioned here #92 has been fixed. Thank you for that!

However, as the below screenshot shows, the Qogir Icon is super blurry.

![Screenshot from 2020-03-18 12-53-30](https://user-images.githubusercontent.com/26806995/76986190-b03a5a80-6917-11ea-8b2e-5654d92017a1.png)

Appreciate it if you could take a look. Thank you!

**Comment by vinceliuice** [comment]
Don't worry, I'll fix this, I'll upload HD version icons for this

**Comment by HymanZHAN** [comment]
Thank you!

**Comment by vinceliuice** [comment]
Fixed!

**Comment by HymanZHAN** [comment]
Thank you!

**Comment by vinceliuice** [comment]
You are welcome!
