### ISSUE TITLE
Functionality for Mountain icon

### ISSUE THREAD

**Issue by GrindamN** [vinceliuice/Qogir-theme#12]
Hi @vinceliuice ,

Would it be possible to add some functionality to mountain icon and how can it be replaced? It would be good to add some dropdown if it is possible or something similar.

**Comment by vinceliuice** [comment]
I also considered this problem, but the menu button of nautilus is not fixed, it can be on the left or right, or you can not use the menu button, so it is not easy to implement this function at present.

**Comment by GrindamN** [comment]
I see. Can we at least modify it to something else or have it removed if we want?

**Comment by vinceliuice** [comment]
Now! I find a way to place this logo to menu button

**Comment by vinceliuice** [comment]
You can check the new theme I update

**Comment by vinceliuice** [comment]
![2018-09-17 14-55-43](https://user-images.githubusercontent.com/7604295/45609378-52ab2080-ba8a-11e8-993e-9d46e2eb817f.png)

**Comment by GrindamN** [comment]
Awesome!

**Comment by GrindamN** [comment]
Just one question, if user wants to change it with other icon what would they have to do?

**Comment by vinceliuice** [comment]
You must use inkscape to modify  Qogir-theme/src/gtk-3.0/assets.svg and then export png files
![screenshot from 2018-10-01 01 05 40](https://user-images.githubusercontent.com/7604295/46260304-bae01480-c516-11e8-9c5a-6e76f93cd0d6.png)

**Comment by vinceliuice** [comment]
Or just replace those logo png files:
![screenshot from 2018-10-01 01 11 42](https://user-images.githubusercontent.com/7604295/46260327-02ff3700-c517-11e8-8b02-aea2d4a4c92b.png)
