### ISSUE TITLE
Change focus color from orange? Request or how-to?

### ISSUE THREAD

**Issue by Dusty919** [vinceliuice/Qogir-theme#124]
Is there any way to change the focus color from orange? I am probably not using the correct term. I'm referring to the focal highlight color that for example highlights the tab you are on in firefox or highlights whatever you have selected in file manager, etc. This color changed to orange when I updated ubuntu to 20.04

It is not that I dislike orange or that I miss the color that it was. I honestly don't know for sure. I think it was blue before? It just looks dumb on my one red laptop and I noticed because it clashes I guess.

If there is not a how to for changing it, I would like to make the request.

**Comment by vinceliuice** [comment]
There are 3 color version you can choose: Qogir: the blue one, Qogir-manjaro: the green one, and Qogir-ubuntu: the orange one, you can use gnome-tweaks to change the theme you are uing

**Comment by Dusty919** [comment]
Thank you, I see now that 20.04 didn't come with all of the versions of this theme pre-installed.

After installing I see that Qogir Dark is the same one as the previous Qogir Budgie Dark one I had before that was blue, and I am OK with just getting back to blue on my red laptop. 

It would be nice though if this focal highlight color was adjustable. Or if there were more than just 3 color variants of this theme.
