### ISSUE TITLE
Cannot change colour of Gnome shell active menu buttons

### ISSUE THREAD

**Issue by Perdyx** [vinceliuice/Qogir-theme#132]
Hello! I would love to fork your theme, but I can't seem to change the colour of the active menu buttons (as well as the activities "..." button)... When I edit the light blue colour in /_sass/_colors.scss it changes everything just fine except for these buttons (also the GTK switches but I don't know if that's the same issue or not). Using a different theme variant such as Ubuntu, changes everything to orange just fine, so I'm a little confused here and not sure if it's an issue with the parse-sass.sh script or something.

Screenshots of what I'm talking about:
![Screenshot from 2020-06-19 20-05-54](https://user-images.githubusercontent.com/29049651/85190014-101f0500-b269-11ea-9c2d-9ecffa9fb9b7.png)
![Screenshot from 2020-06-19 20-06-03](https://user-images.githubusercontent.com/29049651/85190015-11e8c880-b269-11ea-8fc3-205454316934.png)
![Screenshot from 2020-06-19 20-06-08](https://user-images.githubusercontent.com/29049651/85190016-12815f00-b269-11ea-97d1-0526f7919361.png)
![Screenshot from 2020-06-19 20-06-14](https://user-images.githubusercontent.com/29049651/85190017-13b28c00-b269-11ea-9de3-f1de617aee44.png)
![Screenshot from 2020-06-19 20-10-52](https://user-images.githubusercontent.com/29049651/85190018-144b2280-b269-11ea-9062-12abf2dfaa30.png)

**Comment by vinceliuice** [comment]
src/gnome-shell/assets/common-assets/menu/menu-hover.svg

**Comment by vinceliuice** [comment]
You need to change all color assets files
