### ISSUE TITLE
Question: how can I increase the 1px border of the windows to 2px? What do I need to edit?

### ISSUE THREAD

**Issue by Sojiro84** [vinceliuice/Qogir-theme#148]
Hello,

I am on Cinnamon DE.

I searched online, found many options but none of them seem to work when I am editing your theme.
Your theme has a 1px border that I changed the color of as you can see here: 

![image](https://user-images.githubusercontent.com/13678578/87348451-07161080-c555-11ea-8bb4-162d941aa287.png)

I want to increase that border from 1px, to 2px. Can you tell me what I need to change?

I edited metacity-theme-2.xml and metacity-theme-3.xml files, and what I can gather online, one needs to change the following:

```
	<distance name="left_width" value="1" />
	<distance name="right_width" value="1" />
	<distance name="bottom_height" value="1" />
```

But when I change those the following happens:

![image](https://user-images.githubusercontent.com/13678578/87348774-928fa180-c555-11ea-8462-95b8ca704c13.png)

The border disappears! I really need your help. I hope you can tell me what I am missing.

**Comment by Sojiro84** [comment]
Anyone?

**Comment by Sojiro84** [comment]
I am still waiting.

**Comment by Sojiro84** [comment]
Anyone still alive?

Come on, it's a simple question.

**Comment by vinceliuice** [comment]
https://wiki.gnome.org/Attic/GnomeArt/Tutorials/MetacityThemes
------------------
This is very complicated, not as simple as you think. It is not a simple modification of 1> 2. You need to spend 2 line segments on each side.

**Comment by Sojiro84** [comment]
Thanks for responding. It is a shame how complex theming on Cinnamon is.

Guess I shall have to deal with only a 1px border haha!
