### ISSUE TITLE
Minimize - Maximize - Close buttons not visible

### ISSUE THREAD

**Issue by Davide-sd** [vinceliuice/Qogir-theme#15]
Hello Vince,
I've installed this theme with the command "sudo ./Install_with_background_img"
The themes were installed into /usr/share/themes

Unfortunately, the Minimize, Maximize, Close buttons are not visible with any of Qogir themes. I usually keep these buttons on the right of the window. The buttons are still there, If I click the top right corner I can close the windows. But none of them are visible... I'll attach a screenshot.
 
![screenshot from 2018-09-23 22-53-04](https://user-images.githubusercontent.com/9921777/45932862-7e933e00-bf83-11e8-95c5-2875970d6784.png)

**Comment by vinceliuice** [comment]
I'll check this file and fix it

**Comment by vinceliuice** [comment]
is there any issues can see when you run at terminor

**Comment by Davide-sd** [comment]
As far as I can see, no issue at all from the terminal output:

````sudo ./Install_with_background_img  
Start Compile...
==> Generating the gtk.css...
==> Generating the gtk-win.css...
==> Generating the gnome-shell.css...
==> Generating the cinnamon.css...
==> Generating the gtk-light.css...
==> Generating the gtk-win-light.css...
==> Generating the gnome-shell-light.css...
==> Generating the cinnamon-light.css...
==> Generating the gtk-dark.css...
==> Generating the gtk-win-dark.css...
==> Generating the gnome-shell-dark.css...
==> Generating the cinnamon-dark.css...

Compile finished!
Start Install...
Installing '/usr/share/themes/Qogir'...
Installing '/usr/share/themes/Qogir-dark'...
Installing '/usr/share/themes/Qogir-light'...
Installing '/usr/share/themes/Qogir-gnome'...
Installing '/usr/share/themes/Qogir-gnome-dark'...
Installing '/usr/share/themes/Qogir-gnome-light'...

Done.

Install finished!
```

**Comment by vinceliuice** [comment]
It should be works well, I try it on my desktop there is no any issues, maybe you can reboot your system and try again

**Comment by Davide-sd** [comment]
I tryed, no luck :( Also the background image is not visible with Nautilus. I don't understand,  every other themes of yours work great, but Qogir don't. :(

By the way, I'm using Ubuntu 18.04 with GNOME Shell 3.28.3 (ubuntu mode) and GTK+ 3.22.30.

**Comment by Davide-sd** [comment]
I uninstalled them from `/usr/share/themes` and reinstalled into the `~/.themes` 
Everything is working fine now. I believe there were some permission issues. This is strange, because I usually install all my themes into `/usr/share/themes` and I have never had a problem.
