### ISSUE TITLE
Background image in list view

### ISSUE THREAD

**Issue by Lexaromeda** [vinceliuice/Qogir-theme#150]
In Nautlius when I switch to list view, the background image disapear.
![Képernyőkép – 2020-08-16 21-13-47](https://user-images.githubusercontent.com/69767989/90342061-79bb5580-e005-11ea-8cd4-b73aeae0f5c6.png)
![Képernyőkép – 2020-08-16 21-15-55](https://user-images.githubusercontent.com/69767989/90342089-b38c5c00-e005-11ea-92d8-12d2d6733731.png)

**Comment by vinceliuice** [comment]
I'll fix this
