### ISSUE TITLE
Update to GNOME 3.38.

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-theme#153]
There's a few new stuff theme-wise on GNOME 3.38 that make this theme need an update.
You can test it using Fedora 33 pre-release for now :o  
Thanks you!

**Comment by amonforstmann** [comment]
Gnome-Terminal breaks for me with Qogir on Gnome 3.38

![image](https://user-images.githubusercontent.com/1593803/94274739-56f65800-ff46-11ea-8ea1-321b7cd710d4.png)

**Comment by itshaadi** [comment]
same issue as @amonforstmann on Gnome 3.36.6 [archlinux].

**Comment by Micronetic** [comment]
Yep here too, also on Arch GNOME 3.36.6

**Comment by vinceliuice** [comment]
Fixed!
