### ISSUE TITLE
GNOME 3.36.6 Terminal Problems

### ISSUE THREAD

**Issue by Micronetic** [vinceliuice/Qogir-theme#156]
In this closed thread it said it is fixed: https://github.com/vinceliuice/Qogir-theme/issues/153

Downloaded from gnome-look now and this error still happens.

Am on:
Arch 5.8.12 Kernel
GNOME 3.36.6

And now I don't know if it is the Nvidia driver or not but I am using this one: 455.23.04

If you need more infos just tell me.

Edit: When I put Qogir in the Shell setting it is okay, only happens when I put it in the Applications in Gnome Tweaks.

![IMG_0310](https://user-images.githubusercontent.com/57453593/94855034-2aeb4300-042e-11eb-9d95-41c3bd17de16.jpg)

**Comment by vinceliuice** [comment]
You should download from github and install this theme

**Comment by vinceliuice** [comment]
Fixed!
