### ISSUE TITLE
fix text color in gnome shell

### ISSUE THREAD

**Issue by vuminhcongvmc** [vinceliuice/Qogir-theme#157]
![Screenshot from 2020-10-13 23-37-31](https://user-images.githubusercontent.com/45608242/95891495-561b4e00-0daf-11eb-931c-18ff30c3c640.png)
please fix that. thank you.

**Comment by vinceliuice** [comment]
Pop os?

**Comment by vuminhcongvmc** [comment]
yes

**Comment by vinceliuice** [comment]
OK, I'll fix this!
