### ISSUE TITLE
How to uninstall it?

### ISSUE THREAD

**Issue by enzodiaz25** [vinceliuice/Qogir-theme#158]
Hi! I don't find any option in the install.sh script to uninstall the theme. Also, there's no "qogir" folder under ~/.theme.
What should I do?

Thanks in advance.

**Comment by vuminhcongvmc** [comment]
You must uninstall this theme from /usr/share/themes.
$ sudo rm -rf /usr/share/Qogir*

**Comment by jahannivas** [comment]
i have the package but i dont know how to install the themes and changes

**Comment by jahannivas** [comment]
> You must uninstall this theme from /usr/share/themes.
> $ sudo rm -rf /usr/share/Qogir*

how to use this
