### ISSUE TITLE
How to install GDM theme ?

### ISSUE THREAD

**Issue by vuminhcongvmc** [vinceliuice/Qogir-theme#159]
I have installed this theme, but this script don't install GDM theme for me.
Code: $ sudo ./install.sh -t standard -l ubuntu -c standard -g
What I wrong ?

**Comment by vinceliuice** [comment]
I'll check this!

**Comment by vuminhcongvmc** [comment]
> I'll check this!

I have fixed this issue:
* Code changed in install.sh
![image](https://user-images.githubusercontent.com/45608242/97192826-e52a5c00-17da-11eb-9080-f7c8d52a21ee.png)
* Code changed in gnome-shell-theme.gresource.xml
![image](https://user-images.githubusercontent.com/45608242/97192779-d643a980-17da-11eb-837c-096e7ee9158a.png)

**Comment by syne-** [comment]
The gdm theme doesn't work for me either and vuminhcongvmc's changes didn't help.
I have libglib2.0-dev installed and the script copies the files but gdm still looks the same after a reboot.
I'm using ubuntu 20.04.

**Comment by vuminhcongvmc** [comment]
> The gdm theme doesn't work for me either and vuminhcongvmc's changes didn't help.
> I have libglib2.0-dev installed and the script copies the files but gdm still looks the same after a reboot.
> I'm using ubuntu 20.04.

You must choose gresource: 
$ sudo update-alternatives --config gdm3-theme.gresource 
after choose "/usr/share/gnome-shell/gnome-shell-theme.gresource"

**Comment by syne-** [comment]
Thank you.
