### ISSUE TITLE
Gnome 3.38 - Today view not themed

### ISSUE THREAD

**Issue by fguerout** [vinceliuice/Qogir-theme#160]
Hi, "today" view (calendar) that is appearing along side notifications is not "themed".

Example of "qogir dark" mode, "today" view is rendered with default gnome theme (black background)
![image](https://user-images.githubusercontent.com/1132644/98023114-c1809a80-1e06-11eb-989e-b5d0d574e844.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by fguerout** [comment]
Thx, btw incredible project: gtk + shell + icons are all impressive!

**Comment by vinceliuice** [comment]
Fixed!
