### ISSUE TITLE
gnome-shell activity icon

### ISSUE THREAD

**Issue by syne-** [vinceliuice/Qogir-theme#161]
I really don't like the look of the three dots as the icon for activities, so I replaced it with the ubuntu logo.

I think people who care about the nautilus logo would probably like this as well and it could be easily done by just extending the gnome-shell section in the install script like this.
```
  if [[ -f ${SRC_DIR}/src/gtk-3.0/assets/logos/logo-${logo}.svg ]] && [[ ! -z "${logo}" ]] ; then
    cp -r ${SRC_DIR}/src/gtk-3.0/assets/logos/logo-${logo}.svg                       ${THEME_DIR}/gnome-shell/common-assets/misc/activities.svg
    cp -r ${SRC_DIR}/src/gtk-3.0/assets/logos/logo-${logo}.svg                       ${THEME_DIR}/gnome-shell/common-assets/misc/activities-active.svg
  fi
```

**Comment by vinceliuice** [comment]
No problem!
