### ISSUE TITLE
Dark theme in 'Open File' file manager

### ISSUE THREAD

**Issue by williamd5** [vinceliuice/Qogir-theme#162]
I am running the following settings:
![Screenshot from 2020-11-19 15-48-22](https://user-images.githubusercontent.com/66572326/99674450-bb352400-2a7e-11eb-8801-3f1e7ff08c21.png)
However, when you open an upload file/open file dialog (e.g. Ctrl + O in your browser, click "Upload files on discord", or click on a `<input type="file">` element) the theme is white.
![image](https://user-images.githubusercontent.com/66572326/99674851-3bf42000-2a7f-11eb-90ff-c148461a51ef.png)
(left: Discord select file, right: browser upload dialog).
Can't these dialogs be like this one (the `select theme` dialog from Gnome Tweaks)
![image](https://user-images.githubusercontent.com/66572326/99675121-7f4e8e80-2a7f-11eb-94ae-0b64ff29a9c5.png)
Applications theme `yaru-dark` does this successfully.

**Comment by vinceliuice** [comment]
You need install the snap version, if you are using snap apps

**Comment by williamd5** [comment]
Never knew that existed! Thanks, will give it a try

**Comment by williamd5** [comment]
How does that work exactly?
nor
```
sudo snap connect [other snap]:gtk-3-themes qogir-themes:gtk-3-themes
# error: too many arguments for command

```
neither
```
sudo snap connect "[other snap]":gtk-3-themes qogir-themes:gtk-3-themes
# error: snap "[other snap]" has no plug named "gtk-3-themes"
```
seem to be valid commands. Am I missing something here?

**Comment by williamd5** [comment]
Ok, I figured I have to run this for each app.
