### ISSUE TITLE
Text/font colour is too light

### ISSUE THREAD

**Issue by ThornedRose** [vinceliuice/Qogir-theme#165]
Is window text supposed to be this light? In some situations it's difficult to read. 

I'm using Budgie DE on Arch Linux. This screenshot is Budgie Settings against Firefox in the background.

![Screenshot from 2021-01-14 17-01-24](https://user-images.githubusercontent.com/239386/104543453-5535d900-568a-11eb-8cf7-6101dc92750b.png)

I would prefer text to be black or at least dark grey. Is there a way I can make text darker? What do I need to edit to make it darker?

**Comment by vinceliuice** [comment]
Change `$text_color` and `$fg_color` in `../src/_sass/_colors.scss`

**Comment by vinceliuice** [comment]
I'll update this anyway
