### ISSUE TITLE
 [Feature request / Suggestion] Support GTK4

### ISSUE THREAD

**Issue by Tuxino88** [vinceliuice/Qogir-theme#168]
many applications are starting to use gtk4, would it be possible to add support? 

anyway nice theme, the best imho

**Comment by JoaquimCarneiro** [comment]
Agree!! best theme i ever found and Vince one of the best themers! Hope this gets updated to GTK 4 and Gnome 40

**Comment by codic12** [comment]
Matcha has updated to Gtk 4 and Gnome 40, which is excellent. I suspect that Qogir won't be far behind

**Comment by vinceliuice** [comment]
No problem! it'll need some days to finish this job

**Comment by junaru** [comment]
> No problem! it'll need some days to finish this job

Thank you! Your work is much appreciated!

**Comment by sergioad** [comment]
Hey man take your time, please advice us when GNOME 40 is added I would suggest you to use the rounded dash in GNOME shell 40, in my opinion it looks much better than the old rounded corners rectangular dash

**Comment by morsik** [comment]
I would love to see GTK4.0 support also! So far, only Gnome Shell Extensions window is using it, but trying simply symlink `gtk-3.0` theme to `gtk-4.0` obviously doesn't do correct theme :(

![Screenshot from 2021-04-20 14-53-26](https://user-images.githubusercontent.com/783794/115399138-2cbcfe00-a1e8-11eb-9427-514a778bbc58.png)

**Comment by vinceliuice** [comment]
Already supported!

**Comment by morsik** [comment]
@vinceliuice just did `git pull` - works great!

Just found slight inconsistencies in menus from titlebar. Nothing serious, but just giving you hint ;)

GTK3 app (Gnome Tweaks): 
![Screenshot from 2021-04-20 15-00-56](https://user-images.githubusercontent.com/783794/115400291-62aeb200-a1e9-11eb-92b0-238c7ed842a5.png)

GTK4 app (Gnome Shell Extensions): 
![Screenshot from 2021-04-20 15-00-52](https://user-images.githubusercontent.com/783794/115400312-6a6e5680-a1e9-11eb-9897-4a2733a1dd62.png)

**Comment by vinceliuice** [comment]
I'll update this!

**Comment by morsik** [comment]
By the way, I prefer the GTK4 style that looks like normal menu items :D
I never liked those out-of-context menus from GTK3…

**Comment by sergioad** [comment]
Hello, could someone contact the Ubuntu Budgie team to update the qogir budgie 21.04 and add flatpak and snap support for this theme? theme?
