### ISSUE TITLE
gnome-shell.css typo: ransition-animation

### ISSUE THREAD

**Issue by rcragun** [vinceliuice/Qogir-theme#173]
I think I found a CSS typo. This code shows up in my `~/.themes/Qogir/gnome-shell/gnome-shell.css` (and in `gnome-shell.css` for other theme variants):

```
/* Top Bar */
#panel {
  font-weight: bold;
  height: 2.1em;
  min-height: 27px;
  background-color: #21232b;
  border: none;
  font-feature-settings: "tnum";
  ransition-duration: 250ms;
}
```

The last line should say `transition-duration`.

I was not able to find a version number, but I installed the theme by downloading the most recent code from Github on 17 April 2021 around 7am Central Time (USA) and using the included install.sh.

**Comment by vinceliuice** [comment]
Thanks! I'll fix that
