### ISSUE TITLE
compatibility with GNOME 40 just got worse after the last update

### ISSUE THREAD

**Issue by brenoferreiralima** [vinceliuice/Qogir-theme#175]
Before:
![Screenshot from 2021-04-17 19-25-54](https://user-images.githubusercontent.com/4742411/115962124-3f894880-a4f0-11eb-9a12-245d65ef48e7.png)

Now:
![Screenshot from 2021-04-24 11-25-38](https://user-images.githubusercontent.com/4742411/115962141-516aeb80-a4f0-11eb-9c72-7647b06b78ed.png)

**Comment by vinceliuice** [comment]
What's your gnome version?

**Comment by vinceliuice** [comment]
Did you install this theme not on Gnome 40?

**Comment by brenoferreiralima** [comment]
> What's your gnome version?

gnome 40 from arch linux

**Comment by brenoferreiralima** [comment]
> Did you not using Gnome 40 when you install this theme?

i was using... is the same machine and install of the first image

**Comment by vinceliuice** [comment]
Could you download the last update again and reinstall it?

**Comment by brenoferreiralima** [comment]
> Could you download the last update again and reinstall it?

i did... i removed all previous files "rm -rf /usr/share/themes/Qogir*" then downloaded again in a new folder with "git clone https://github.com/vinceliuice/Qogir-theme/" ... then i did a new install with "install.sh" script.... and still the same

**Comment by brenoferreiralima** [comment]
but the version from https://www.gnome-look.org/p/1230631/ works with no problems... just the latest git version is broke

**Comment by vinceliuice** [comment]
I updated it again, could you try the last one?

**Comment by brenoferreiralima** [comment]
> I updated it again, could you try the last one?

its perfect again now, thank you to answer and correct so quickly! <3
