### ISSUE TITLE
Transparent header bar background in Apostrophe

### ISSUE THREAD

**Issue by aperezdc** [vinceliuice/Qogir-theme#177]
The header bar in the [Apostrophe](https://somas.pages.gitlab.gnome.org/apostrophe/) application (version 2.4) shows as transparent, causing graphics glitches:

![Apostrophe screenshot](https://user-images.githubusercontent.com/723451/117662420-35ca3b00-b1a8-11eb-8947-93ebdadec8d7.png)

The above screenshot is using the Qogir theme built from Git commit b63c74d

**Comment by Tuxino88** [comment]
yeah break apostrophe

![photo_2021-05-28_12-55-41](https://user-images.githubusercontent.com/75674245/119973637-0858fc00-bfb4-11eb-817a-4f41cfb68e39.jpg)

**Comment by vinceliuice** [comment]
You are welcome!
