### ISSUE TITLE
Wider window borders on xfwm, please?

### ISSUE THREAD

**Issue by HolyBlackCat** [vinceliuice/Qogir-theme#179]
This theme is absolutely gorgeous, but 1 pixel window borders in xfwm make it hard to resize windows.

Even 2 pixel borders would improve the situation.

**Comment by HolyBlackCat** [comment]
Decided to do it myself: https://github.com/vinceliuice/Qogir-theme/pull/180

**Comment by HolyBlackCat** [comment]
I see you implemented 2px borders, thanks!

**Comment by vinceliuice** [comment]
You are welcome!
