### ISSUE TITLE
Close Button is clipped on Hover

### ISSUE THREAD

**Issue by JoshHouser** [vinceliuice/Qogir-theme#18]
As seen in the following screen shot the close button is clipped when hovering over it.

![close button overlap](https://user-images.githubusercontent.com/4361528/47321607-22671c80-d60a-11e8-9cca-21435a343527.png)

Currently using Linux Mint 19 Cinnamon.

**Comment by vinceliuice** [comment]
Just download the new theme and try again, because I don't have this issue on my cinnamon

**Comment by vinceliuice** [comment]
Fixed now

**Comment by JoshHouser** [comment]
Yeay, the new update works like a charm.
