### ISSUE TITLE
Nautilus scroll bar on the wrong side

### ISSUE THREAD

**Issue by algent-al** [vinceliuice/Qogir-theme#183]
Hi, I have this strange issue with Qogir Theme.
The scrollbar is on left and I think it should be on the right.
![qogir-error](https://user-images.githubusercontent.com/46356616/120362150-09b75b00-c30b-11eb-9e63-866781c85762.png)

Other info:
OS: Solus Budgie
Nautilus: version 40.1
libgkt-3: version: 3.24.29

**Comment by vinceliuice** [comment]
Only Qogir have this issue？ this seems like a app issue not theme issue

**Comment by algent-al** [comment]
Found that the issue is with Nautilus window size. If it is short enough that it cant fit all items on the right then the scroll bar appears like in the picture. If you extend Nautilus window at the bottom to make sure all items on the left are fit, then the scroll bar go to the right. Saw the same behaviour with Matcha theme too.

![qogir-issue](https://user-images.githubusercontent.com/46356616/120517926-45b4f380-c3d1-11eb-802e-9bb3a13dcbd8.gif)

**Comment by algent-al** [comment]
Closing since it isn't a real issue.
