### ISSUE TITLE
Flatpak GTK4 apps not themed.

### ISSUE THREAD

**Issue by ayushr01** [vinceliuice/Qogir-theme#185]
I am running qogir-win-dark with the org.gtk.Gtk3theme.Qogir-win-dark flatpak package. GTK3 Flatpak apps are themed perfectly but GTK4 flatpak apps like WhatIP and gnome extensions are not.

GTK3 Flatpak: 
![image](https://user-images.githubusercontent.com/22570553/123092042-ad49e600-d447-11eb-9a93-053774a2c1ca.png)

GTK4 Flatpak: 
![image](https://user-images.githubusercontent.com/22570553/123092092-bdfa5c00-d447-11eb-831b-950e2cba1d4d.png)

Is there anyway I can resolve this?

**Comment by OckhamOdyssey** [comment]
Same problem here. Any solution?

**Comment by olddesklamp** [comment]
How can this be closed as completed when no solution is provided?
