### ISSUE TITLE
Selecting multiple items in Thunar

### ISSUE THREAD

**Issue by mehedirm6244** [vinceliuice/Qogir-theme#186]
Images speak better
![selection_a](https://user-images.githubusercontent.com/86041547/125809929-1b2440cf-4c3b-4b94-aee4-408c72eb7a01.png)
This is ... umm... sorry I don't know what it's called. But this looks how it's supposed to be.
But in Thunar,
![selection_thunar](https://user-images.githubusercontent.com/86041547/125810025-31a2c32a-99f9-4c18-b127-dacafc999a49.png)
The background of this thing is completely transparent. I can't get any clue for fixing this issue. Can you help a bit over here? This issue appears in Thunar when using "Icon view". It works fine on list or compact view
Sorry for my bad explanation. Looking forward to get replied

**Comment by the-saddest-clown** [comment]
Same here. Xfce DE.
And you can see there are some artifacts doing this so something needs to be fixed here.
![artifacts](https://user-images.githubusercontent.com/83234199/132811405-45bf99b0-5732-4177-b395-9f26930f22e6.png)

**Comment by vinceliuice** [comment]
I'll fix this
