### ISSUE TITLE
Cinnamon tray icons context menu broken on first click.

### ISSUE THREAD

**Issue by Jazzhoo** [vinceliuice/Qogir-theme#188]
First of all, great theme, as always from this creator! 

Unfortunately, I get the same issue with other @vinceliuice 's theme 'WhiteSur'
I tried on both Linux Mint and Manjaro, Both running Cinnamon 5.0.5 (I had version 4 before and the issue was the same.)
My tray area applet is: XApp Status Applet + System tray
I've experimented with different themes and the issue is not there.

The issue:
Applications affected: Skype, Discord, Teams, Warpinator (possibly more application sharing same tray context mechanism)
When I click on certain tray icons for the first time, they look broken. Closing the context window and opening again fixes it. However, still, very annoying seeing such a beautiful themes with bug like that. 

Below the screens of both broken context windows (1st click) and fixed (2nd click):
![20210806_095615](https://user-images.githubusercontent.com/53535260/128486705-49ff0d6d-e5c2-4ddf-8a16-1c742e502ac9.jpg)
![20210806_095646](https://user-images.githubusercontent.com/53535260/128486788-77d5bd2e-6061-4c7a-896a-e1cec4f58873.jpg)
![20210806_095540](https://user-images.githubusercontent.com/53535260/128486811-cc37de5f-9470-498a-9796-b5e76eef5ae5.jpg)

And now the fixed:

![20210806_095500](https://user-images.githubusercontent.com/53535260/128486860-96c64209-8ac9-4082-b7e0-af13805c09a2.jpg)
![20210806_095510](https://user-images.githubusercontent.com/53535260/128486870-b39c9b08-d09d-444d-8be3-9d994ef19867.jpg)
![20210806_095548](https://user-images.githubusercontent.com/53535260/128486881-c97c5e1e-e5a0-4085-b5e9-4273556c4ea5.jpg)

**Comment by vinceliuice** [comment]
Fixed!
