### ISSUE TITLE
Missing Ubuntu and Manjaro colors

### ISSUE THREAD

**Issue by fossraven** [vinceliuice/Qogir-theme#193]
When I run the install.sh after cloning the repository the colors Ubuntu and Manjaro are missing. It works when I use ./install.sh -t manjaro or -t ubuntu.

![qogir-install-sh](https://user-images.githubusercontent.com/76121935/131252579-76bafb01-2a95-49a4-b2a9-f8511470ab9c.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed

**Comment by vinceliuice** [comment]
Run `./install.sh -t all` top install them
