### ISSUE TITLE
[Qogir, Qogir-Dark bugs] Menu problems in Gimp, Visual Studio Code

### ISSUE THREAD

**Issue by ceyhunnabiyev** [vinceliuice/Qogir-theme#2]

**Comment by vinceliuice** [comment]
The first version was made in a hurry, so there will be many problems. I will solve these bugs in the future.

**Comment by GrindamN** [comment]
Hi Vince, the issue with GIMP is still present with the GIMP as of today, as well with Firefox on dark theme.

**Comment by vinceliuice** [comment]
Fixed now
