### ISSUE TITLE
Small space above tab in Firefox

### ISSUE THREAD

**Issue by LeoKesler** [vinceliuice/Qogir-theme#20]
Hello,

I like your theme. Thank you for give the choice of using big square buttons, because I hate the small buttons, it is hard to click. 

But I have a small issue: using Firefox, there is a small space above the tab. Look above the thin blue line in tab:

![space_above_tab](https://user-images.githubusercontent.com/5854679/47534475-daf0c280-d88d-11e8-8e7e-8064daf9e90f.png)

It is small but annoying. When you have some time, can you try to fix this issue ?

Best regards.

**Comment by vinceliuice** [comment]
Removed now
