### ISSUE TITLE
Requesting for Rounded window corners

### ISSUE THREAD

**Issue by gokul1630** [vinceliuice/Qogir-theme#201]
Please Add Option for Rounded Window Corners.

**Comment by vinceliuice** [comment]
Finished!

Run:
```sh
./install.sh --tweaks round
```
to install it

**Comment by gokul1630** [comment]
thanks 🤩

**Comment by ltGuillaume** [comment]
Should this work in Budgie, too? I removed `/usr/share/themes/Qogir-manjaro-dark` to be sure, pulled the last commit and used the command `sudo ./install.sh -t manjaro -c dark -g --tweaks round --tweaks image` and applied the theme. All windows and popups are still square.

**Comment by vinceliuice** [comment]
It should be `sudo ./install.sh -t manjaro -c dark -g --tweaks round image`

**Comment by gokul1630** [comment]
just now i cloned & installed latest theme, still windows & menu corners are squared
i'm using linux mint cinnamon
![image](https://user-images.githubusercontent.com/43679827/142354736-8d08e4a0-9f77-4598-aa29-89d05140c685.png)

**Comment by vinceliuice** [comment]
Now the gnome-shell rounded version is finished!

**Comment by ltGuillaume** [comment]
Thanks!!

**Comment by ltGuillaume** [comment]
By the way, doesn't `[image|square|round]` imply that it's "either, or", _not_ that you can "chain" them together, like `--tweaks round image`? It's a bit confusing imho.

**Comment by vinceliuice** [comment]
Options all can mix use

**Comment by ltGuillaume** [comment]
I just thought `|` would imply OR, so you'd need another `--tweaks` for more than one of these options (but then tweak__s__ wouldn't make sense).

Ok, I just pulled the latest commit, removed `/usr/share/themes/Qogir-manjaro-dark` to be sure, then reinstalled with `sudo ./install.sh -t manjaro -c dark -g --tweaks round image`, but no dice: none of the windows and popups have rounded corners in Budgie. Too bad.

**Comment by vinceliuice** [comment]
![Screenshot from 2021-11-18 23-33-45](https://user-images.githubusercontent.com/7604295/142446079-3eb79e90-a1cb-4653-995d-bd44d3bb0adc.png)
It works on my desktop with no issue!

**Comment by ltGuillaume** [comment]
That's not the Manjaro theme

**Comment by gokul1630** [comment]
i pulled the latest commits & installed theme but still rounded corners only applied for browsers & but not other windows or menus. i'm using linux mint cinnamon 20.2.

![image](https://user-images.githubusercontent.com/43679827/142627205-b6311f7a-5836-4a57-ab36-60ce14c9196e.png)
![image](https://user-images.githubusercontent.com/43679827/142627220-55b278a5-8b5f-484c-ac31-c81de9fcb976.png)

**Comment by vinceliuice** [comment]
metacity theme is not finished, just need to wait some time
