### ISSUE TITLE
FreeBSD 已添加软件仓库

### ISSUE THREAD

**Issue by liulitchi** [vinceliuice/Qogir-theme#205]
刚查看了一下。 Qogir 主题和图标都已被 FreeBSD 仓库收入。安装方式如下：

- Qogir Theme ：`pkg install qogir-gtk-themes`

- Qogir Icon: `pkg install qogir-icon-themes`

在 FreeBSD 13 测试了一下，运行良好，你可以更新一下 ReadMe 。

**Comment by vinceliuice** [comment]
好的，没问题
