### ISSUE TITLE
[Feature] Plank Theme

### ISSUE THREAD

**Issue by Gabb1995** [vinceliuice/Qogir-theme#21]
Are there plans to add a plank theme as well?
Arc offer one here https://github.com/horst3180/arc-theme/tree/master/extra/Arc-Plank and its the one I usually go with but would be nice to see if you could come up with a plank theme that matches Qogir.

**Comment by vinceliuice** [comment]
You can download the new one here, I already added a plank theme for Qogir when I fixed elementary issues

**Comment by Gabb1995** [comment]
oh wow nice didnt even realise! thanks for the great work.
