### ISSUE TITLE
[Bug] GDM theme shows not properly 

### ISSUE THREAD

**Issue by Anifyuli** [vinceliuice/Qogir-theme#212]
![IMG_20211229_162536](https://user-images.githubusercontent.com/73734843/147647747-a164626c-5ec0-440d-8bcc-c5c20a55f942.jpg)

Hello, Bro. I ask to you about this bug (see above this text).

Icon and password form shows not properly, but in login screen show perfectly. This bug on your previous release was also encountered. I want you fix that problem. Thanks for your perfect work.

Keep spirit and sorry my English

See you on next update

**Comment by vinceliuice** [comment]
What's your gnome version?

**Comment by Anifyuli** [comment]
GNOME 41.2, Bro

**Comment by vinceliuice** [comment]
OK, I'll fix it

**Comment by Anifyuli** [comment]
Thanks, Bro. I will wait your progress

**Comment by vinceliuice** [comment]
Fixed!

**Comment by Anifyuli** [comment]
Wow, its awesome. Thanks, Bro

**Comment by vinceliuice** [comment]
You are welcome!
