### ISSUE TITLE
Theme not working for GTK3 apps in Xubuntu 16.04

### ISSUE THREAD

**Issue by wojciechrak** [vinceliuice/Qogir-theme#22]
Hi, I've installed theme from gnome-look.org (https://www.gnome-look.org/p/1230631/).
Extracted files from archive and copied over to `~/.themes`.
Then opened *Appearance* and changed theme to *Qogir-dark*.
![Appearance](http://i.imgur.com/guifGZr.png)

Everything looks OK, except for GTK3 applications.
Gnome Software
![Screenshot](http://i.imgur.com/pYZHhxF.png)

Plank settings
![Plank](http://i.imgur.com/88ZUnEy.png)

I am using Xubuntu 16.04.

**Comment by vinceliuice** [comment]
Sorry ubuntu 16.04 not surpported, you should update your gtk3 version to gtk 3.20

**Comment by wojciechrak** [comment]
After updating to 18.04 with gtk 3.22, everything works fine. Thanks
