### ISSUE TITLE
libadwaita support?

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-theme#222]
Will it be possible to add support for apps theming with libadwaita? AFAIK you can use a env variable to theme them.

**Comment by vinceliuice** [comment]
Libadwaita not support 3rd part themes

**Comment by pewduckwei** [comment]
hi vince, i found a post about theming in libadwaita
https://www.reddit.com/r/gnome/comments/tp3v7d/theming_in_libadwaita_is_pretty_nice/?utm_medium=android_app&utm_source=share

**Comment by vinceliuice** [comment]
No perfect but that works!

**Comment by pewduckwei** [comment]
Hopefully in the future, it can be customized, very sad if it doesn't support it. Even though Qogir is the theme I've always used since 2018

**Comment by vinceliuice** [comment]
Me too, hope gnome team will support that!

**Comment by vinceliuice** [comment]
Fixed!
