### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by Marivishnu** [vinceliuice/Qogir-theme#226]
I upgraded my machine to Pop!_OS 22.04 running Gnome 42 and found some problems.
1) While hovering over the menus, the text is not visible
![image](https://user-images.githubusercontent.com/67962094/165675418-8862a937-e990-4491-bcf7-1cf7940f7c86.png)

2) Clicking the option doesn't change the selected theme color (I use Qogir-Majaro-Dark)
![image](https://user-images.githubusercontent.com/67962094/165675581-b16e893e-04b7-4974-bb62-7554c4eac366.png)

**Comment by vinceliuice** [comment]
Fixed!
