### ISSUE TITLE
Error Install --tweaks square

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#231]
GNOME Shell 42.0
Install Square titlebutton version ...
Installing '/usr/share/themes/Qogir'...
Error: The target selector was not found.
       Use "@extend %small_titlebutton !optional" to avoid this error.
        on line 256 of src/_sass/gtk/apps/_misc.scss
>>         @extend %small_titlebutton;

   ----------------^
Error: The target selector was not found.
       Use "@extend %small_titlebutton !optional" to avoid this error.
        on line 256 of src/_sass/gtk/apps/_misc.scss
>>         @extend %small_titlebutton;

   ----------------^
Install Square titlebutton version ...
Installing '/usr/share/themes/Qogir-Light'...
Error: The target selector was not found.
       Use "@extend %small_titlebutton !optional" to avoid this error.
        on line 256 of ../../../../../home/azrizal/Downloads/Qogir-theme/src/_sass/gtk/apps/_misc.scss
>>         @extend %small_titlebutton;

   ----------------^
Error: The target selector was not found.
       Use "@extend %small_titlebutton !optional" to avoid this error.
        on line 256 of ../../../../../home/azrizal/Downloads/Qogir-theme/src/_sass/gtk/apps/_misc.scss
>>         @extend %small_titlebutton;

   ----------------^
Install Square titlebutton version ...
Installing '/usr/share/themes/Qogir-Dark'...
Error: The target selector was not found.
       Use "@extend %small_titlebutton !optional" to avoid this error.
        on line 256 of ../../../../../home/azrizal/Downloads/Qogir-theme/src/_sass/gtk/apps/_misc.scss
>>         @extend %small_titlebutton;

   ----------------^
Error: The target selector was not found.
       Use "@extend %small_titlebutton !optional" to avoid this error.
        on line 256 of ../../../../../home/azrizal/Downloads/Qogir-theme/src/_sass/gtk/apps/_misc.scss
>>         @extend %small_titlebutton;

   ----------------^

Done.

**Comment by vinceliuice** [comment]
Fixed!
