### ISSUE TITLE
XFCE, Chrome window buttons are not rendered

### ISSUE THREAD

**Issue by HolyBlackCat** [vinceliuice/Qogir-theme#233]
This is how windows buttons look for me in Chrome:
![pic](https://user-images.githubusercontent.com/20289055/168484734-b6fce2d2-50dc-40c3-ad33-be6d24cdb6d6.png)

Hovering or clicking makes them red (the last one) or black (the other two).

In other applications the buttons are rendered correctly.

I've installed Chrome natively, without Snap.

**Comment by HolyBlackCat** [comment]
This seems to be caused by the fix of #230

**Comment by vinceliuice** [comment]
I'll fix this
