### ISSUE TITLE
Ubuntu 22.04 Screen Capture Menu.

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#234]
Hello, I think need to fix for Gnome-Shell screen capture for Ubuntu and Chrome browser. The format is broken now.

![image](https://user-images.githubusercontent.com/38023611/168713779-780dd057-ff0f-442e-954f-ed1cf351f6cd.png)

![image](https://user-images.githubusercontent.com/38023611/168714072-67057439-29c7-4504-aa70-22f677cb9538.png)

https://linuxhint.com/methods-take-screenshots-ubuntu/

**Comment by vinceliuice** [comment]
Fixed!
