### ISSUE TITLE
"Take A Screenshot" Menu for Ubuntu 22.04 error.

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#235]
Hello Vince,
Great for you fast respond to fixed few errors previously and I love this theme design and should be default for Ubuntu 22.04. For today, I notice the "Take A Screenshot" menu have weird UI and not follow the theme settings. Below is the screencast's preview:

https://user-images.githubusercontent.com/38023611/168941993-9ee4ea1a-3b09-416b-bf26-e2e8dece5747.mp4

and here the default menu theme.

![image](https://user-images.githubusercontent.com/38023611/168942023-cc2e39df-5c31-41fa-a381-6b3a354c6953.png)

Thank You! :)

**Comment by BuLLHACK** [comment]
I think @vinceliuice should take a look at this, I can confirm this bug exists as of the writing of this post.
