### ISSUE TITLE
RTL problem

### ISSUE THREAD

**Issue by mskf1383** [vinceliuice/Qogir-theme#238]
Hi
![نماگرفت از 2022-05-27 12-22-27](https://user-images.githubusercontent.com/50908329/170655853-a77211fa-8901-4509-8808-79989852cef3.png)

- Nautilus icon is on left
- Wrong blue color position in Nautilus sidebar

Please fix it.
Thanks!

**Comment by vinceliuice** [comment]
How to set RTL?

**Comment by mskf1383** [comment]
My system language is Persian (a RTL language). You can try this command to open Nautilus with persian language (It may be English because you don't have language files, but it is RTL):
```
export LANG=fa_IR.UTF-8;  nautilus
```
