### ISSUE TITLE
Cannot get nautilus background image

### ISSUE THREAD

**Issue by JoshHouser** [vinceliuice/Qogir-theme#24]
As instructed I used the following command after using "cd Qogir-theme":

**./Install -m --image**

The terminal produced the following:
Specify theme with nautilus background image ...
==> Generating the gtk.css...
==> Generating the gtk-gnome.css...
==> Generating the gnome-shell.css...
==> Generating the cinnamon.css...
==> Generating the gtk-light.css...
==> Generating the gtk-gnome-light.css...
==> Generating the gnome-shell-light.css...
==> Generating the cinnamon-light.css...
==> Generating the gtk-dark.css...
==> Generating the gtk-gnome-dark.css...
==> Generating the gnome-shell-dark.css...
==> Generating the cinnamon-dark.css...
Installing '/home/josh/.themes/Qogir'...
Installing '/home/josh/.themes/Qogir-light'...
Installing '/home/josh/.themes/Qogir-dark'...
Installing '/home/josh/.themes/Qogir-gnome'...
Installing '/home/josh/.themes/Qogir-gnome-light'...
Installing '/home/josh/.themes/Qogir-gnome-dark'...

Done.

The nautilus background does not show. Is there a final step that we are supposed to do? I reset the OS with no change, tried out other Qogir theme variations that also did not display the background. On a side note I accidentally used the --square option and want to revert back to non square.

- A Mountain Enthusiast

**Comment by JoshHouser** [comment]
I see the background image referenced in: **../.themes/Qogir/gtk-3.0/gtk.css**

.nautilus-window,
.nautilus-window notebook,
.nautilus-window notebook > stack {
  background-image: -gtk-scaled(url("assets/backimage.png"), url("assets/backimage@2.png"));
  background-repeat: no-repeat;
  background-position: bottom right;
}

The file is it's a respective directory. Not sure why it's not loading or displaying properly.

**Comment by vinceliuice** [comment]
You should run ./Install -i -s,   if you add -m, you need options: standard or gnome

**Comment by vinceliuice** [comment]
![_nautilus_20181114093239](https://user-images.githubusercontent.com/7604295/48454210-67d5ce80-e7f1-11e8-9d51-0ed3ff443c95.png)

**Comment by JoshHouser** [comment]
For the sake of making this as simple as possible I

- swapped back to the default Cinnamon theme
- deleted theme(s) from /home/user/.themes.
- downloaded theme files via Terminal with: git clone https://github.com/vinceliuice/Qogir-theme
- then added the line cd Qogir-theme
- followed by ./Install -i -s
- swapped to the Qogir theme

**Comment by vinceliuice** [comment]
Your nautilus still have no background img?

**Comment by vinceliuice** [comment]
That should not be, It work well on my desktop (gnome)

**Comment by JoshHouser** [comment]
Everything is working great except for the background. I'm running Linux Cinnamon 19.

**Comment by vinceliuice** [comment]
Are you using nautilus for file manager app? because this only work for nautilus, I did not set this for Cinnamon default file manager: nemo.

**Comment by JoshHouser** [comment]
I'm not using Nautilus. I assumed the background picture came with the theme when specified in the options.

**Comment by JoshHouser** [comment]
Is there interest in making the background work for the standard file manager view?

**Comment by vinceliuice** [comment]
Different file managers have different widgets, I don't know if other can have this, but I will try to let nemo have this background img first.

**Comment by vinceliuice** [comment]
Now I add support for nemo and thunar, you can try again

**Comment by JoshHouser** [comment]
I appreciate your assistance. Thanks for creating this beautiful theme which I plan on porting over to my other devices. Long story I swapped away from Windows and considered getting a Mac in part due to it's elegant interface. However Linux is much more inline with an ideal open ended operating system.

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by JoshHouser** [comment]
Really appreciate you adding it. Now if only I could undo the square look (I placed in -s and can't seem to undo it).

**Comment by vinceliuice** [comment]
When you run -s, that will change the source files, we can not undo it
