### ISSUE TITLE
Installing Qogir Only Themes Legacy Applications

### ISSUE THREAD

**Issue by SlamminCO** [vinceliuice/Qogir-theme#246]
Installing the latest release (2022-05-29) with `sudo ./install.sh` installs the theme for Legacy Applications, but libadwaita applications do not change.

![image](https://user-images.githubusercontent.com/100872889/173152794-e1440e10-8e33-409e-b2c7-54a1711b8e7c.png)

![image](https://user-images.githubusercontent.com/100872889/173153173-bf2e5d9b-32f3-403a-acfe-0904749c6a96.png)

**OS**: Arch Linux
**GNOME Version**: 42.2 (X11)

**Comment by vinceliuice** [comment]
Do not run it with sudo

**Comment by SlamminCO** [comment]
Thank you, that solved the issue
