### ISSUE TITLE
Error opening file - Permission denied.

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#247]
Hello,
Do i install it wrong?

gnome-shell[5069]: Failed to load file:///usr/share/themes/Qogir-Ubuntu-Dark/gnome-shell/assets/activities.svg: Error opening file /usr/share/themes/Qogir-Ubuntu-Dark/gnome-shell/assets/activities.svg: Permission denied

Thank You,

**Comment by BuLLHACK** [comment]
Make sure the Dir where you put the files does not have any spaces in it. Hope this helps.

**Comment by kred-jon** [comment]
yup! the path don't have any space *it's default main path actually: usr/share/themes/Qogir-Ubuntu-Dark/gnome-shell/assets/activities.svg

![image](https://user-images.githubusercontent.com/38023611/180692072-f0b0d785-0e47-42a0-8862-7398f4197c7f.png)

**Comment by kred-jon** [comment]
I found the solution, need to chmod 755 the Qogir's folder
