### ISSUE TITLE
Firefox - Wrong color on dark theme

### ISSUE THREAD

**Issue by Flying--Dutchman** [vinceliuice/Qogir-theme#248]
### Color when switched inside Firefox to dark theme:

![grafik](https://user-images.githubusercontent.com/9158539/176394194-a56f4826-92e9-40bb-aacd-1f3262f62138.png)

<br> <br> <br>

### Color when switched on OS to dark theme:

![grafik](https://user-images.githubusercontent.com/9158539/176395100-9621d66a-8520-4301-b8ef-7c279f7c3775.png)

**Comment by vinceliuice** [comment]
Not support switched inside Firefox

**Comment by Flying--Dutchman** [comment]
Ah okay. Thank you for your quick response :+1:
