### ISSUE TITLE
Separator button between cancel and authenticate looks uncomfortable

### ISSUE THREAD

**Issue by supanadit** [vinceliuice/Qogir-theme#252]
![image](https://user-images.githubusercontent.com/33617149/184523076-4d40e1c4-9618-4141-b064-dbc64864835a.png)

I think it shouldn't have white separator between those button

Gnome Version: 42.4
Distribution: Arch Linux
Package Manager to Install Qogir Theme: AUR

**Comment by supanadit** [comment]
I am forget to mention, is that come from theme issue or gnome issue ?

**Comment by vinceliuice** [comment]
Fixed
