### ISSUE TITLE
SDDM Enter button isn't square

### ISSUE THREAD

**Issue by S0nter** [vinceliuice/Qogir-theme#255]
I was trying to fix it for 2 hours, but without any result.
Please fix it

**Comment by vinceliuice** [comment]
What sddm theme you are using?

**Comment by S0nter** [comment]
> Какую тему sddm вы используете?

**Comment by S0nter** [comment]
Qogir (0.1.0) by Vince Liuice

**Comment by vinceliuice** [comment]
![IMG_20220928_102006.jpg](https://user-images.githubusercontent.com/7604295/192672829-3efd4422-02e2-4db3-9159-0d1f4f60763f.jpg)

**Comment by vinceliuice** [comment]
I did not find that issue

**Comment by S0nter** [comment]
There's no problem at the first screen, but on the second something went wrong

**Comment by S0nter** [comment]
![20220928_192538](https://user-images.githubusercontent.com/108224581/192834622-df0388e9-0cb7-40fc-83cb-a43d06e01d70.jpg)
