### ISSUE TITLE
[Question]  What sets the interface font colors in Firefox?

### ISSUE THREAD

**Issue by ajruckman** [vinceliuice/Qogir-theme#26]
I am trying to figure out what sets the font colors for things like the URL bar and the menu in Firefox, they are a little too dark for my preference. I have tried changing `$text_color` and `$fg_color` and that changed the colors of other interface items like bookmark names and tab titles, but not everything.

Menu: https://i.imgur.com/hWLtOuN.png
URL bar: https://i.imgur.com/B9ITFUk.png

Thanks for the great work!

**Comment by vinceliuice** [comment]
It's on line 289 of /src/_sass/gtk/apps/_misc.scss, 
Any way I'll also think it's a little dark, so I change it to $text_color
