### ISSUE TITLE
Waiting update for Gnome V43.0

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#261]
Hello All,
Waiting an update for Gnome V43.0, notify us once completed.

![image](https://user-images.githubusercontent.com/38023611/198220526-6de67228-2fda-482c-9e7d-9b7ac9d98820.png)

**Comment by ofer5183** [comment]
qogir it's the best . hope it will work with gnome 43 and change the new nautilis view like on gnome 42..
