### ISSUE TITLE
[Bug (?)] White theme on some apps / settings

### ISSUE THREAD

**Issue by Pheggas** [vinceliuice/Qogir-theme#267]
Hello. I installed Qogir theme today and absolutely love it. However on some windows / apps / settings windows this theme applies but in it's white (light) version, not the dark one i chose.

Example:
Nautilus - dark as it should be
![image](https://user-images.githubusercontent.com/9994511/200186788-afdc824f-1d01-4863-baf2-11cf1c75ba95.png)

Desktop -> Right click -> Change background - White version of theme that i didn't choose
![image](https://user-images.githubusercontent.com/9994511/200186849-337110f9-1266-4cd5-b4ca-057a8ed8fb4b.png)

Open files dialog - White version of theme that i didn't choose
![image](https://user-images.githubusercontent.com/9994511/200186897-6f088db6-758f-4e0c-bac7-d2ecde294495.png)

Is there any simple fix on this? I think this is error in install.sh file that i used to install the theme.

**Comment by vinceliuice** [comment]
Run `./install.sh -l -c light`

**Comment by Pheggas** [comment]
Alright. I didn't know some of the apps requires to specify color variant instead of chosen color.

For anyone who found this: i ran my command as it is but added `-c dark` to "force" dark theme.

Final command:
`./install.sh  -i fedora --tweaks round -l -c dark`
