### ISSUE TITLE
INSTALL script problem

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#277]
Hello,
I try install using install.sh

sudo ./install.sh -d /usr/share/themes/ -t ubuntu -i ubuntu -g -l --tweaks square

But nothing install in the /usr/share/themes folder.

Thank You.

**Comment by kred-jon** [comment]
Feedback from script after fire the command:

GNOME Shell 42.5
Install Square titlebutton version ...

Install Qogir-Ubuntu-Dark GDM Theme...

Done.

**Comment by vinceliuice** [comment]
If you use -g option it will only install gdm theme

**Comment by vinceliuice** [comment]
Run `sudo ./install.sh -t ubuntu -i ubuntu --tweaks square` again, it will install into `/usr/share/themes`, and do not use `-l` with sudo, it can not work
