### ISSUE TITLE
有些柱状条颜色被覆盖了

### ISSUE THREAD

**Issue by FateRover** [vinceliuice/Qogir-theme#28]
![avatar](https://imgur.com/vMTw24Kl.png)
xfce4-systemload-plugin　　　这个插件，颜色是可以自定义的，但是本主题会强制覆盖为蓝色
![avatar](https://imgur.com/XdXYAsDl.png)

**Comment by vinceliuice** [comment]
好的,我看看是哪的代码覆盖了自定义

**Comment by FateRover** [comment]
暂时先不要排查了，我发现我两台电脑上这个主题表现不一样，可能是我的问题。

**Comment by vinceliuice** [comment]
😂好的
