### ISSUE TITLE
Issue with Nemo

### ISSUE THREAD

**Issue by juandejesuss** [vinceliuice/Qogir-theme#282]
on Qogir theme when I hover on any Marker of nemo it appears all white, I attach a capture, if you could only fix that, I'd appreciate it a lot friend, thanks in advance!!!

![imagen](https://user-images.githubusercontent.com/3791171/221759310-88de3aa1-6c2e-40f1-99ae-34db1360a94a.png)

**Comment by fblais** [comment]
I get the same thing!
Cinnamon 5.6.8 here. (LMDE 5)

**Comment by juandejesuss** [comment]
> I get the same thing! Cinnamon 5.6.8 here. (LMDE 5)

Now Ubuntu Budgie 23.04 has this issue too ='(

**Comment by vinceliuice** [comment]
Fixed now

**Comment by juandejesuss** [comment]
> Fixed now

It works now!!! thanks a lot [vinceliuice](https://github.com/vinceliuice)!!!
