### ISSUE TITLE
--tweaks option missing from 2023-02-27 release

### ISSUE THREAD

**Issue by elderehrlich** [vinceliuice/Qogir-theme#283]
New install of Fedora 37, followed all prerequisite steps and upon running 
sudo ./install.sh -t all --tweaks image round

I also tried it with the option '--tweaks  image' and either way get the following error:

ERROR: Unrecognized installation option '--tweaks '. 

I checked both help options and see that the command option '--tweaks ' is not listed now. Checked against an older install on another machine and it is listed. Was this option removed or is this a bug? 

If by design, how do I install the image for Files / Nautilus?

I noticed tht there are other install.sh options missing as well.

**Comment by vinceliuice** [comment]
![截图 2023-03-04 17-08-06](https://user-images.githubusercontent.com/7604295/222887858-0d6033fc-02bf-4295-b756-4b8e9a2ade8f.png)
Did not find this issue

**Comment by elderehrlich** [comment]
Hmmm, curious. Okay I will give it another go.

**Comment by elderehrlich** [comment]
Redownloaded the source.zip and worked like it always has. Must have been a corrupted download the first time around. Sorry for the trouble Vince, happy to close this one as no bug status.
