### ISSUE TITLE
GTK in KDE, Cinnamon. Title buttons have wrong icons.

### ISSUE THREAD

**Issue by evgeniy-harchenko** [vinceliuice/Qogir-theme#284]
I use this theme for GTK apps in KDE Plasma. All work good except title buttons. They use default Breeze textures. Examples of buggy apps: _gedit_, _bleachbit_, _pamac_, _chromium(with gtk theme)_.
![1](https://user-images.githubusercontent.com/42656259/224377359-90042228-55d1-4b0d-863b-3a9975d2b2d5.png)
The problem apeared in version 2022-05-29 after [commit 136f9f8](https://github.com/vinceliuice/Qogir-theme/commit/136f9f81ce122f5cc3ef3e2fed9405ae2c3b9d90).

**Update:** same with all apps in Cinnamon (tested on Manjaro and EndeavourOS). Theme uses strange (may be fallback) title button icons.
![3](https://user-images.githubusercontent.com/42656259/224993888-f5bc59d0-03dc-4b89-9084-fa54a439167f.png)

**Comment by Dejweed** [comment]
The title buttons follow the icon theme. Try changing the icon theme and see if it there's a difference.

**Comment by evgeniy-harchenko** [comment]
Yes, I forgot to mention that. There is normal icons in title buttons when I use Qogir-icon-theme. But I want to use other icons theme. Is there any possibility to built in icons in theme?

**Comment by Dejweed** [comment]
Looking at #232 it appears that built-in icons were removed to avoid bugs. The easiest thing for you would be to copy the window buttons from [Qogir icon theme](https://github.com/vinceliuice/Qogir-icon-theme) to your other icon theme. It isn't a perfect solution but it will get the job done. The icons you need are located at `symbolic/actions`.

- window-minimize-symbolic
- window-restore-symbolic
- window-maximize-symbolic
- window-close-symbolic

Go to your icon theme, find the directory with these icons and replace them.

I hope this is helpful :)

**Comment by evgeniy-harchenko** [comment]
Yes it works, thanks! And is it normal that these apps have a bit smaller icons and red color of close button is pinky?
![2](https://user-images.githubusercontent.com/42656259/232782958-291d5d3d-9b1b-4ec2-9945-2043b36d26da.png)
Top - Gimp, bottom - gedit.

**Comment by evgeniy-harchenko** [comment]
Checked your variant. Yes, now GTK and KDE apps are almost the same. Top - gedit, bottom - konsole:
![3](https://user-images.githubusercontent.com/42656259/233104638-a76bc7fc-cfe4-4063-8b19-20147b621f8b.png)
gedit close button is darker because its window is unfocused (close button in KDE apps does not fade when its on unfocused window). But as for me, bright red colour like in original theme looks better.

Also I tried to play with GTK theme on XFCE. Same thing. All apps look good, except _gedit, bleachbit, pamac, chromium(with gtk theme)_. They have pinky close button and it becomes darker when its window is unfocused.

Finnaly I tried to use Metacity WM on XFCE. It makes all apps have pinky close buttons. So apps look almost the same with Metacity. Only excepted apps like gedit have darker close button when its window is unfocused.

**Comment by Dejweed** [comment]
If you want you can tweak the color to your liking. To make the close button red in apps like gedit, find the `gtk-3.0/gtk.css` or `gtk-3.0/gtk-dark.css` file and edit it. The lines you are looking for are `headerbar button.titlebutton.close:hover` and `headerbar button.titlebutton.close:active`. You can change the background-color to whatever you want. It looks like this:
> headerbar button.titlebutton.close:hover, .titlebar button.titlebutton.close:hover {
>   background-color: #d7787d;
>   color: white;
> }
> 
> headerbar button.titlebutton.close:active, .titlebar button.titlebutton.close:active {
>   background-color: #be3841;
>   color: white;
> }

`#d7787d` is the pinky color and `#be3841` is used when the button is pressed. You could also just replace every `#d7787d` with `#ff5555` and `#be3841` with `#c83737`, if that's what you want.

So if you want to match it with the KDE theme it should look like this:
> headerbar button.titlebutton.close:hover, .titlebar button.titlebutton.close:hover {
>   background-color: #ff5555;
>   color: white;
> }
> 
> headerbar button.titlebutton.close:active, .titlebar button.titlebutton.close:active {
>   background-color: #c83737;
>   color: white;
> }

I'm not sure about the inactive colors. 

And if you want to change the red color in the KDE theme you need to edit `aurorae/themes/Qogir/close.svg`. Again just replace the colors with what you want.

This should give you what you want :)

**Comment by evgeniy-harchenko** [comment]
Many thanks, I think we dealt with it.
![12](https://user-images.githubusercontent.com/42656259/233397072-08b31c21-c610-4cab-9b6b-39b3f61832bf.png)

Yes, sizes are a bit different. But it seems there is no point to change it because google-chrome has smaller buttons than KDE apps, while gedit has bigger.

I also created pull request with fix in [Qogir-icon-theme](https://github.com/vinceliuice/Qogir-icon-theme/pull/94).

**Comment by Dejweed** [comment]
Hmmm, it's been a month and no response yet. Looks like this is not what the author wants.
