### ISSUE TITLE
Support for GNOME 44

### ISSUE THREAD

**Issue by I-Iawk** [vinceliuice/Qogir-theme#285]
Like [Lavanda Issue #11](https://github.com/vinceliuice/Lavanda-gtk-theme/issues/11), this theme doesn't support "Enhanced Quick Settings" in GNOME 44

If I come across any other bugs, I'll update them here.

**Comment by kred-jon** [comment]
Hello,
Gnome 44 found problem with dark themes as below.

![image](https://github.com/vinceliuice/Qogir-theme/assets/38023611/3eb5e422-6b81-4627-8867-32afe102b2b8)

**Comment by vinceliuice** [comment]
Fixed now @kred-jon

**Comment by vinceliuice** [comment]
Run: `./install.sh -l`

**Comment by vinceliuice** [comment]
Run `./install.sh -t ubuntu -c standard` to install the theme you are using for libadwaita app

**Comment by kred-jon** [comment]
sudo ./install.sh -d /usr/share/themes/ -i ubuntu -t ubuntu -l --tweaks square

GNOME Shell 44.0
Install Square titlebutton version ...
Installing '/usr/share/themes//Qogir-Ubuntu'...
Install Square titlebutton version ...
Installing '/usr/share/themes//Qogir-Ubuntu-Light'...
Install Square titlebutton version ...
Installing '/usr/share/themes//Qogir-Ubuntu-Dark'...

Link '/usr/share/themes//Qogir-Ubuntu-Light/gtk-4.0' to '/root/.config/gtk-4.0' for libadwaita...

Done.

**Comment by vinceliuice** [comment]
Restart you desktop

**Comment by kred-jon** [comment]
not only desktop, i have rebooted the computer too

**Comment by vinceliuice** [comment]
Do not run this `./install.sh -d /usr/share/themes/ -i ubuntu -t ubuntu -l --tweaks square` with sudo

**Comment by vinceliuice** [comment]
just run it without sudo

**Comment by kred-jon** [comment]
Somehow it working now:

![image](https://github.com/vinceliuice/Qogir-theme/assets/38023611/c47fa2e7-926e-41a5-a48c-0d5feb1a10f2)

With using the same command:

 sudo ./install.sh -d /usr/share/themes/ -i ubuntu -t ubuntu -l --tweaks square
GNOME Shell 44.0
Install Square titlebutton version ...
Installing '/usr/share/themes//Qogir-Ubuntu'...
Install Square titlebutton version ...
Installing '/usr/share/themes//Qogir-Ubuntu-Light'...
Install Square titlebutton version ...
Installing '/usr/share/themes//Qogir-Ubuntu-Dark'...

Link '/usr/share/themes//Qogir-Ubuntu-Light/gtk-4.0' to '/root/.config/gtk-4.0' for libadwaita...

Done.

Can I change the themes in libadwaita from Qogir-Ubuntu-Light to Qogir-Ubuntu?

**Comment by kred-jon** [comment]
OK I realize that if the path is under  "/usr/share/themes/" the functionality is less that it's should. We need to install in the user path.

Thank you!
