### ISSUE TITLE
Qogir-Dark GTK theme

### ISSUE THREAD

**Issue by bstone-suse** [vinceliuice/Qogir-theme#292]
The lower menu at the bottom right does not display correctly.  It works find with the Qogir regular theme, but if you switch to Qogir Dark, the menu appears rounded and not wide enough for the arrow icons to display.
![Screenshot from 2023-05-24 10-53-06](https://github.com/vinceliuice/Qogir-theme/assets/78875917/0e114843-3936-4935-870f-c60a159fc2dc)

**Comment by vinceliuice** [comment]
Download the last update and try again

**Comment by bstone-suse** [comment]
I tried this, no joy.  It is not install correctly.  Is it possible to upload the files to Gnome-Look where you had these previously?  I pull from there and I have to problem installing.

**Comment by bstone-suse** [comment]
Or, is it possible to just download a tar file from here to update what I currently have.  I attempted to replace the files in their respective places and that did not work either.  Totally messed it up.

**Comment by vinceliuice** [comment]
Did you install it from github?

**Comment by bstone-suse** [comment]
That is what I attempted to do.  I'm running openSUSE Tumbleweed.  The files that you have in the install script do not exist.  If when I created them in the ~/home directory, still didn't work.

**Comment by vinceliuice** [comment]
The files that you have in the install script do not exist ? What error info did you get when you run: `./install.sh`

**Comment by bstone-suse** [comment]
It attempted to install files to /usr/share/themes - which would have been fine, but it also attempted to install to ~/home/$name/.themes which doesn't exist, so the script failed.

**Comment by vinceliuice** [comment]
When you run `./install.sh` script will make `~/.themes` folder, it doesn't matter if it is not exist, just run `./install.sh`

**Comment by bstone-suse** [comment]
No joy.  I've reloaded what I previously had.  I think the problem is in the css file alone.  I'm comparing the regular to dark, as the normal one shows up perfectly.

**Comment by vinceliuice** [comment]
The install script will detect your gnome-shell version and install the appropriate version based on your desktop version，could you just run ./install.sh and show me a screenshot  of your output, also you can show me a screen shot of your gnome-tweaks theme settings. I tested on my fedora 38，but did not find this issue， by the way when you try to install it don't forget download the last update on github for testing

**Comment by vinceliuice** [comment]
![Screenshot from 2023-05-25 18-38-44](https://github.com/vinceliuice/Qogir-theme/assets/7604295/14e0cb4b-44bf-435b-9628-be0916e9f25e)

**Comment by bstone-suse** [comment]
I have the non-rounded corners, which is great.  It is the System Menu which you display at the top right that is rounded still and the arrows are covered or outside the bounds of the system menu.
![Qogir-Dark-ScreenShot](https://github.com/vinceliuice/Qogir-theme/assets/78875917/55b99cfc-8862-4ce1-9bcd-d8c14a181ca2)

**Comment by bstone-suse** [comment]
This is the output from running the install.sh

GNOME Shell 44.1
./install.sh: line 722: ./clean-old-theme.sh: No such file or directory
Installing '/usr/share/themes/Qogir'...
cp: cannot stat '//COPYING': No such file or directory
cp: cannot stat '//AUTHORS': No such file or directory
cp: cannot stat '//src/gtk-2.0/apps.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/panel.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/main.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/xfce-notify.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/assets/assets': No such file or directory
cp: cannot stat '//src/gtk-2.0/theme/gtkrc': No such file or directory
cp: cannot stat '//src/gtk-2.0/menubar-toolbar.rc': No such file or directory
cp: cannot stat '//src/gtk/assets/assets': No such file or directory
 icon not supported, default icon will install...
cp: cannot stat '//src/gtk/assets/logos/logo-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/logos/logo@2-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/assets-common/*': No such file or directory
cp: cannot stat '//src/gtk/theme-3.0/gtk.css': No such file or directory
cp: cannot stat '//src/gtk/theme-3.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/assets/thumbnail.png': No such file or directory
cp: cannot stat '//src/gtk/assets/assets': No such file or directory
 icon not supported, default icon will install...
cp: cannot stat '//src/gtk/assets/logos/logo-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/logos/logo@2-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/assets-common/*': No such file or directory
cp: cannot stat '//src/gtk/theme-4.0/gtk.css': No such file or directory
cp: cannot stat '//src/gtk/theme-4.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/assets/thumbnail.png': No such file or directory
cp: cannot stat '//src/gnome-shell/common-assets': No such file or directory
cp: target '/usr/share/themes/Qogir/gnome-shell/assets': No such file or directory
cp: cannot stat '//src/gnome-shell/assets/assets/*.svg': No such file or directory
 icon not supported, Qogir icon will install...
cp: cannot stat '//src/gnome-shell/logos/logo-qogir.svg': No such file or directory
cp: cannot stat '//src/gnome-shell/icons': No such file or directory
cp: cannot stat '//src/gnome-shell/pad-osd.css': No such file or directory
cp: cannot stat '//src/gnome-shell/theme-44-0/gnome-shell.css': No such file or directory
cp: cannot stat '//src/cinnamon/assets/common-assets': No such file or directory
cp: cannot stat '//src/cinnamon/assets/assets': No such file or directory
cp: cannot stat '//src/cinnamon/cinnamon.css': No such file or directory
cp: cannot stat '//src/cinnamon/thumbnail.png': No such file or directory
cp: cannot stat '//src/metacity-1/assets/*.png': No such file or directory
cp: cannot stat '//src/metacity-1/metacity-theme-3.xml': No such file or directory
cp: cannot stat '//src/metacity-1/metacity-theme-1.xml': No such file or directory
cp: cannot stat '//src/metacity-1/thumbnail.png': No such file or directory
cp: cannot stat '//src/plank': No such file or directory
cp: cannot stat '//src/unity': No such file or directory
cp: cannot stat '//src/xfce-notify-4.0': No such file or directory
Installing '/usr/share/themes/Qogir-Light'...
cp: cannot stat '//COPYING': No such file or directory
cp: cannot stat '//AUTHORS': No such file or directory
cp: cannot stat '//src/gtk-2.0/apps.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/panel.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/main.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/xfce-notify.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/assets/assets': No such file or directory
cp: cannot stat '//src/gtk-2.0/theme/gtkrc-Light': No such file or directory
cp: cannot stat '//src/gtk-2.0/menubar-toolbar-Light.rc': No such file or directory
cp: cannot stat '//src/gtk/assets/assets': No such file or directory
 icon not supported, default icon will install...
cp: cannot stat '//src/gtk/assets/logos/logo-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/logos/logo@2-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/assets-common/*': No such file or directory
cp: cannot stat '//src/gtk/theme-3.0/gtk-Light.css': No such file or directory
cp: cannot stat '//src/gtk/theme-3.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/assets/thumbnail.png': No such file or directory
cp: cannot stat '//src/gtk/assets/assets': No such file or directory
 icon not supported, default icon will install...
cp: cannot stat '//src/gtk/assets/logos/logo-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/logos/logo@2-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/assets-common/*': No such file or directory
cp: cannot stat '//src/gtk/theme-4.0/gtk-Light.css': No such file or directory
cp: cannot stat '//src/gtk/theme-4.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/assets/thumbnail.png': No such file or directory
cp: cannot stat '//src/gnome-shell/common-assets': No such file or directory
cp: target '/usr/share/themes/Qogir-Light/gnome-shell/assets': No such file or directory
cp: cannot stat '//src/gnome-shell/assets/assets/*.svg': No such file or directory
 icon not supported, Qogir icon will install...
cp: cannot stat '//src/gnome-shell/logos/logo-qogir.svg': No such file or directory
cp: cannot stat '//src/gnome-shell/icons': No such file or directory
cp: cannot stat '//src/gnome-shell/pad-osd.css': No such file or directory
cp: cannot stat '//src/gnome-shell/theme-44-0/gnome-shell.css': No such file or directory
cp: cannot stat '//src/cinnamon/assets/common-assets': No such file or directory
cp: cannot stat '//src/cinnamon/assets/assets': No such file or directory
cp: cannot stat '//src/cinnamon/cinnamon.css': No such file or directory
cp: cannot stat '//src/cinnamon/thumbnail.png': No such file or directory
cp: cannot stat '//src/metacity-1/assets-Light/*.png': No such file or directory
cp: cannot stat '//src/metacity-1/metacity-theme-3.xml': No such file or directory
cp: cannot stat '//src/metacity-1/metacity-theme-1-Light.xml': No such file or directory
cp: cannot stat '//src/metacity-1/thumbnail-Light.png': No such file or directory
cp: cannot stat '//src/plank': No such file or directory
cp: cannot stat '//src/unity': No such file or directory
cp: cannot stat '//src/xfce-notify-4.0': No such file or directory
Installing '/usr/share/themes/Qogir-Dark'...
cp: cannot stat '//COPYING': No such file or directory
cp: cannot stat '//AUTHORS': No such file or directory
cp: cannot stat '//src/gtk-2.0/apps.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/panel.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/main.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/xfce-notify.rc': No such file or directory
cp: cannot stat '//src/gtk-2.0/assets/assets-Dark': No such file or directory
cp: cannot stat '//src/gtk-2.0/theme/gtkrc-Dark': No such file or directory
cp: cannot stat '//src/gtk-2.0/menubar-toolbar-Dark.rc': No such file or directory
cp: cannot stat '//src/gtk/assets/assets': No such file or directory
 icon not supported, default icon will install...
cp: cannot stat '//src/gtk/assets/logos/logo-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/logos/logo@2-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/assets-common/*': No such file or directory
cp: cannot stat '//src/gtk/theme-3.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/theme-3.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/assets/thumbnail-Dark.png': No such file or directory
cp: cannot stat '//src/gtk/assets/assets': No such file or directory
 icon not supported, default icon will install...
cp: cannot stat '//src/gtk/assets/logos/logo-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/logos/logo@2-.svg': No such file or directory
cp: cannot stat '//src/gtk/assets/assets-common/*': No such file or directory
cp: cannot stat '//src/gtk/theme-4.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/theme-4.0/gtk-Dark.css': No such file or directory
cp: cannot stat '//src/gtk/assets/thumbnail-Dark.png': No such file or directory
cp: cannot stat '//src/gnome-shell/common-assets': No such file or directory
cp: target '/usr/share/themes/Qogir-Dark/gnome-shell/assets': No such file or directory
cp: cannot stat '//src/gnome-shell/assets/assets-Dark/*.svg': No such file or directory
 icon not supported, Qogir icon will install...
cp: cannot stat '//src/gnome-shell/logos/logo-qogir.svg': No such file or directory
cp: cannot stat '//src/gnome-shell/icons': No such file or directory
cp: cannot stat '//src/gnome-shell/pad-osd.css': No such file or directory
cp: cannot stat '//src/gnome-shell/theme-44-0/gnome-shell-Dark.css': No such file or directory
cp: cannot stat '//src/cinnamon/assets/common-assets': No such file or directory
cp: cannot stat '//src/cinnamon/assets/assets-Dark': No such file or directory
cp: cannot stat '//src/cinnamon/cinnamon-Dark.css': No such file or directory
cp: cannot stat '//src/cinnamon/thumbnail-Dark.png': No such file or directory
cp: cannot stat '//src/metacity-1/assets/*.png': No such file or directory
cp: cannot stat '//src/metacity-1/metacity-theme-3.xml': No such file or directory
cp: cannot stat '//src/metacity-1/metacity-theme-1.xml': No such file or directory
cp: cannot stat '//src/metacity-1/thumbnail.png': No such file or directory
cp: cannot stat '//src/plank': No such file or directory
cp: cannot stat '//src/unity': No such file or directory
cp: cannot stat '//src/xfce-notify-4.0': No such file or directory
cp: cannot stat '//src/xfwm4/themerc': No such file or directory
cp: cannot stat '//src/xfwm4/assets/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc': No such file or directory
cp: cannot stat '//src/xfwm4/assets-hdpi/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc': No such file or directory
cp: cannot stat '//src/xfwm4/assets-xhdpi/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc-Light': No such file or directory
cp: cannot stat '//src/xfwm4/assets-Light/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc-Light': No such file or directory
cp: cannot stat '//src/xfwm4/assets-Light-hdpi/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc-Light': No such file or directory
cp: cannot stat '//src/xfwm4/assets-Light-xhdpi/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc': No such file or directory
cp: cannot stat '//src/xfwm4/assets/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc': No such file or directory
cp: cannot stat '//src/xfwm4/assets-hdpi/*.png': No such file or directory
cp: cannot stat '//src/xfwm4/themerc': No such file or directory
cp: cannot stat '//src/xfwm4/assets-xhdpi/*.png': No such file or directory

Done.

**Comment by vinceliuice** [comment]
Download this: https://github.com/vinceliuice/Qogir-theme/archive/refs/heads/master.zip
Then unzip it, make sure all files are ok, open the terminal at unziped folder then run `./install.sh`
![Screenshot_20230526_020642](https://github.com/vinceliuice/Qogir-theme/assets/7604295/59f7146b-39e7-4d16-8415-8292b373d118)

**Comment by bstone-suse** [comment]
Excellent!  The last solution installed perfectly.  Thanks much!

**Comment by vinceliuice** [comment]
run ./install.sh -l

**Comment by bstone-suse** [comment]
Vince,

Okay great.  That fixed most of it, but the window seems to only appear in Qogir theme, not in Qogir-Dark.  It's livable, but I'm reading through the rest of the documentation.  This has to be the best theme out there.

Thanks,

Blaine

​​​[cid:7de34d56-6135-45cc-aaab-b547d9202dfa]

A. Blaine Stone
Certification Compliance Program Manager

SUSE
+1 (202) 316-5501
***@***.***

Washington, DC

www.suse.com<http://www.suse.com>
________________________________
