### ISSUE TITLE
Theme not working for Nautilus (Files) 44.1

### ISSUE THREAD

**Issue by canha** [vinceliuice/Qogir-theme#293]
I'm running the current version of Arch Linux which has Files (Nautilus) version 44.1, but the theme isn't applied and the default theme remains.

I've tried with both light and dark versions, any help is appreciated.

**Comment by vinceliuice** [comment]
Run `./install.sh -l`

**Comment by canha** [comment]
Oh, I totally missed that! Many thanks, seems to be working perfectly.
