### ISSUE TITLE
Latest Version - Fedora 38 - Gnome 44.3

### ISSUE THREAD

**Issue by kevinbburns** [vinceliuice/Qogir-theme#299]
On dual screens, the top bar dropdown menu is getting cut off.
![20230824_102005](https://github.com/vinceliuice/Qogir-theme/assets/825269/8d9f81f4-1070-43c7-99d4-a42a88d3aaa6)

**Comment by vinceliuice** [comment]
Download the last update on github and reinstall it, it will choose the right gnome-shell theme for your desktop

**Comment by kevinbburns** [comment]
I will try that shortly. I had modified the gnome-shell CSS file with the following to get it to fit right:

`.quick-settings {
  /*padding: 12px !important;*/
  padding: 18px;
  border-radius: 0px !important;
  margin-top: 6px !important;
  margin-right:8px;
}

.quick-toggle {
  border-radius: 0px;
  min-width: 8em;
  max-width: 10em;
  min-height: 40px;
  border: 1px solid rgba(255, 255, 255, 0.12);
  /* Move padding into the box; this is to allow menu arrows
     to extend to the border */
}`

It is working perfectly now.

![image](https://github.com/vinceliuice/Qogir-theme/assets/825269/66e9b70d-4c98-41ba-a011-1fb988fe8645)

**Comment by kevinbburns** [comment]
Pulling straight from the repo and installing worked perfectly! Thank you for the help.
