### ISSUE TITLE
No border with popup menu at menubar. Without compton not useable.

### ISSUE THREAD

**Issue by agxy** [vinceliuice/Qogir-theme#31]
Hi vinceliuice.
First I would like to thank you for that wonderful theme. It's the first theme I really enjoy it.
Unfortunately your last update 3 days ago comes with no border around the popup menu at the menubar anymore. Without compton it doesn't make sense.

![2018-12-28](https://user-images.githubusercontent.com/46232120/50531753-7d6f3100-0add-11e9-839a-b4a9d54dc425.png)

Is there a way to get the border back again?
Cheers 
agxy

**Comment by vinceliuice** [comment]
OK, I'll fix this

**Comment by vinceliuice** [comment]
Are you using xfce4.13 desktop?

**Comment by vinceliuice** [comment]
Fixed now
