### ISSUE TITLE
Dash to panel pinned apps are moving

### ISSUE THREAD

**Issue by mineLdiver** [vinceliuice/Qogir-theme#317]
After enabling Qogir (latest from GitHub) on my Arch with Gnome, hovering over dash to panel pinned apps started slightly moving them vertically on each hover.

First position:
![image](https://github.com/vinceliuice/Qogir-theme/assets/19170211/8524882c-9a83-4f09-a66f-073dc70fe057)

Second position:
![image](https://github.com/vinceliuice/Qogir-theme/assets/19170211/8962c1e9-cdcd-4781-9144-bd08636f9d4b)

Things tried:
1. Restoring dash to panel thickness, app margin/padding to default. Didn't change anything.
2. Using Adwaita icons. Didn't change anything.

**Comment by mineLdiver** [comment]
Another thing: I can't disable Qogir for some reason now. Specifically in Dash to Panel. It's no longer in Tweaks, and nothing uses it anymore, but Dash to Panel, somehow.

**Comment by mineLdiver** [comment]
Nevermind the above comment. Somehow, only uninstalling the GDM theme and rebooting again fixed Dash to Panel theme. I'll stick to Adwaita until the moving apps issue is figured out.

**Comment by mineLdiver** [comment]
Decided to try again. I guess the moving issue is somehow related to this selection, since it doesn't seem to fit fully into the panel. Is it possible to somehow remove it?
![image](https://github.com/vinceliuice/Qogir-theme/assets/19170211/e794f45d-b783-435c-aa5f-00c9f9fcae61)
![image](https://github.com/vinceliuice/Qogir-theme/assets/19170211/081ef87d-cee4-4bdc-b126-c0d39a53c0dc)

**Comment by farmerbb** [comment]
I have this same issue, and was able to bisect it down to this commit: https://github.com/vinceliuice/Qogir-theme/commit/110c69082ba1adae809172f5725dc7ba4078095f

**Comment by vinceliuice** [comment]
Fixed
