### ISSUE TITLE
Dash to panel border issue

### ISSUE THREAD

**Issue by emmggi** [vinceliuice/Qogir-theme#326]
![Screenshot from 2024-07-19 08-32-08](https://github.com/user-attachments/assets/ef75dc73-b5e3-42ce-b808-9610c8701dcd)

I cannot seem to remove this border on hover. It's only present when qogir is selected.

I'm enabling the theme through the extensions user themes window. 

Arc and Adwaita don't have this issue.

I'm using Gnome and EndeavourOS. These are versions of packages:
```
aur/qogir-gtk-theme 2024.05.22-1 (+12 0.00) (Installed)
endeavouros/eos-qogir-icons 5-1 (4.9 MiB 22.4 MiB) (Installed)
```

**Comment by vinceliuice** [comment]
Fixed
