### ISSUE TITLE
Metacity windows buttons are not squared

### ISSUE THREAD

**Issue by h1aji** [vinceliuice/Qogir-theme#33]
Minimize,maximize and close button stays rounded even if you specify -s option when install.

Looks like this option is not supported for metacity wm.

is it possible to fix?

**Comment by vinceliuice** [comment]
Sorry, square version don't support metacity and xfwm for now

**Comment by horca** [comment]
Is this the reason why Firefox (without title bar) has circle windows buttons even with squared theme installed? Version with title bar has correct button style.

**Comment by vinceliuice** [comment]
Fixed now
