### ISSUE TITLE
XFCE4 Mousepad trouble

### ISSUE THREAD

**Issue by Hierosme** [vinceliuice/Qogir-theme#331]
The Dark theme version have trouble with XFCE4 Mousepad:

- Selected line
- Line number
- 
Everything stay white, without any difference.
Then it's iust impossible to read the line number or the selected line text.

## Like that:
![image](https://github.com/user-attachments/assets/c73a60d5-37c8-4129-ae0c-796045f4c416)

## Information

- Xfce 4.18
- Gtk 3.24.43
- Mousepad 0.6.2

**Comment by vinceliuice** [comment]
open `view` > `Color Scheme` change aother color theme

**Comment by Hierosme** [comment]
Thanks @vinceliuice ,

Yes few colorshemes work , few others not.

I have supposate , by chose view > Color Scheme > none i'll let the Theme impose it colors (then finaly colorsheme)

The **None** for colorsheme is the **default** value, it is for that i have repport trouble, because look like a trouble.
I'm confuse because it happen too with  Arc-theme Dark and Adwaita Dark themes.

What that mean ? The trouble should be address to XFCE Mousepad team ?
Nothing Qogir-theme can fixe due to a lake of touchable object ?

Regards

**Comment by vinceliuice** [comment]
`Mousepad` and `Gedit` ... all gtk editor default color scheme (none) are `classic`, I don't why use this color scheme, all have this issue

**Comment by vinceliuice** [comment]
And I can certainly say this this a app color scheme issue, because all gtk theme have issue, and we can not change this color from gtk theme

**Comment by Hierosme** [comment]
I close that issue, the xfce4 ticket have been close, look to be a global issue.

Classic and Tango style schemes: set 'text' style and others to avoid inheriting GTK default colors
https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/279
