### ISSUE TITLE
A margin on the left side of the button on the head bar

### ISSUE THREAD

**Issue by happystraw** [vinceliuice/Qogir-theme#34]
环境:

- 系统: Ubuntu 18.04

- 主题: Qogir

安装选项:

- `./Install -s -i`

问题描述:

- 部分程序顶部栏按钮左侧没有顶格, 存在留白.

- e.g. `gnome-terminal`, `firefox`, `gimp`, `visual studio code`, other base on electron, etc.

预览:

![screenshot from 2019-01-09 09-50-01](https://user-images.githubusercontent.com/18533666/50871181-d00dee80-13f5-11e9-8bd9-e4bf32cc37a3.png)

谢谢!

**Comment by vinceliuice** [comment]
好的,我测试一下

**Comment by vinceliuice** [comment]
好了, 现在没问题了, 我已经修复了
