### ISSUE TITLE
Budgie Raven is huge when over 100% volume bar requested

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/Qogir-theme#38]
![ubuntu budgie - new development bionic running - oracle vm virtualbox 1_121](https://user-images.githubusercontent.com/996240/52522631-bf17fd80-2c7f-11e9-95c4-9aa0f4c4bd69.png)

Using Ubuntu Budgie 18.10/19.04 but would equally apply with an up-to-date Manjaro Budgie or Solus Budgie (does not apply to Ubuntu Budgie 18.04 unless you are running with the UB backports PPA)

If you remove the calendar widget from raven and tick the over 100% volume setting in budgie-desktop-settings - Raven ... then logout and login, raven is shown as above.

Upstream budgie desktop keep closing bug reports such as this via a "use a recognised compatible theme such as Plata"

Plata styles this slider bar that has a tick mark using https://gitlab.com/tista500/plata-theme/blob/master/src/gtk/sass/common/_3rd-party.scss#L868

**Comment by vinceliuice** [comment]
Thanks, I'll fix this

**Comment by fossfreedom** [comment]
Looked really nice.  Cheers for the fix :)
