### ISSUE TITLE
Just showing you a theme I made from Qogir-dark

### ISSUE THREAD

**Issue by freefreeno** [vinceliuice/Qogir-theme#40]
This is not done nor is it a guarantee it will stay like this but I have gone about as far as I can with it. I was just trying to learn. If you wanted to take this this and go further with it you could or not it doesn't matter.

![screenshot_2019-02-24_11-41-38](https://user-images.githubusercontent.com/41884680/53302884-2e1d5680-3829-11e9-9fef-207f6733d4f9.png)
 ![screenshot_2019-02-24_11-35-50](https://user-images.githubusercontent.com/41884680/53302846-9b7cb780-3828-11e9-9e2c-c1efb385d553.png)
![screenshot_2019-02-24_11-36-13](https://user-images.githubusercontent.com/41884680/53302849-9ddf1180-3828-11e9-88f7-41fcee1d5e14.png)

**Comment by vinceliuice** [comment]
Looks great! keep on man!
