### ISSUE TITLE
Ubuntu 19.04 GNOME Control Center header

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/Qogir-theme#42]
GNOME devs decided to revert/change the styling of GNOME Control Center again.  I'm guessing that now GNOME 3.32 is in frozen state, this means the styling will not change again (hopefully)

So you can see the white bar with the latest git master

![image](https://user-images.githubusercontent.com/996240/53957849-5df51580-40d7-11e9-8b34-1ed6f80fba50.png)

Ubuntu 19.04 - the new GNOME Control Center version popped into the release channel yesterday.

**Comment by vinceliuice** [comment]
Fixed now
