### ISSUE TITLE
Strange scrollbar in XFCE 4.12 in Geany

### ISSUE THREAD

**Issue by Peter-Ries** [vinceliuice/Qogir-theme#43]
Hi,

first of all thanks for your great work. I love this theme!

I'm facing a weird issue in Geany (V. 1.33) and Xubuntu 18.04.2.

The scrollbar of the main edit window gets duplicated or looks like in the 80ies Arcade Game "Worm". 

When I use the PgUp/Down the scrollbar shows up multiple times (and shaded. If  I scroll with arrow keys it gets a fade out look. 

Tested with mouspad editor. There the scrollbar looks ok. 

Screenies: https://paste.pics/eeb9c7d4a029d8a35ce4c4b5dd0c92c5
and https://paste.pics/a378088871256842838aa2e6d4f5e2c3

nothing serious but strange...

BR
Peter

**Comment by vinceliuice** [comment]
It seems not a issue about gtk theme

**Comment by Peter-Ries** [comment]
it's just qogir in combination with geany...
geany and any other theme is OK
qogir with any app != geany is OK, too

So don't worry, it's absolutely minor and I'm currently switching over to another editor/ide anyway

;)

Regards
Peter
