### ISSUE TITLE
Theme broken after update

### ISSUE THREAD

**Issue by mamen2022** [vinceliuice/Qogir-theme#45]
Hi,
I have the following setup Ubuntu 18.04 with Gnome shell version 3.28.3. I am using this theme over a year now, but I didn't update since January I think. Yesterday I updated to the current version and on my pc, the theme is completely broken now.. and i cant even downgrade because the Install script wrote on top of my old version and I couldnt find online a list of previous versions..

1º - The close, maximize and minimize don't show up. The buttons are there but invisible.  

![Screenshot from 2019-03-20 17-37-07](https://user-images.githubusercontent.com/9058507/54706507-03c46d80-4b37-11e9-9c6a-3d6bfd5b32ad.png)

2º - CheckBoxes and bullets on Forms dont show up either..

3º - The gnome shell got all screwed up also

![Screenshot from 2019-03-20 17-39-32](https://user-images.githubusercontent.com/9058507/54706572-26568680-4b37-11e9-9523-8255cbf03252.png)

4º - On the README you refere to a "-m, --menu | appmenu button variant(s) (standard/gnome)" option but in the Install script there isn't any. Is this related to the issues?

Please help, this is the most awsome theme and I dont want to switch.
Using my computer is currently a pain without Qogir Theme!

**Comment by vinceliuice** [comment]
All png and svg image files missing, you check this folder:
![2019-03-21 08-20-04 的屏幕截图](https://user-images.githubusercontent.com/7604295/54727350-48d9b580-4bb2-11e9-89d0-09683adeab79.png)
If those files missing or read only, you can delete all theme files and reinstall this theme (and you can reboot your system to make sure it works).

**Comment by mamen2022** [comment]
Solved ;)
