### ISSUE TITLE
flags on gnome-mines game

### ISSUE THREAD

**Issue by algent-al** [vinceliuice/Qogir-theme#46]
gnome-mines game.
Flags on game should be black instead of white.
![gnome-mines Qogir-Theme](https://user-images.githubusercontent.com/46356616/54908347-f79a3080-4ee7-11e9-8dc8-cc794ea8b01b.png)
Same problem on all three Qogir themes
Qogir, Qogir Dark and Qogir Light.

In general the theme is fantastic.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Sorry, I find this flag is contoled by icon theme, it can not be changed by gtk theme

**Comment by algent-al** [comment]
Oh, I see. I am sorry for that. Changed icon theme and now is OK.

Thank you!
