### ISSUE TITLE
Date/Clock color switches to blue on click

### ISSUE THREAD

**Issue by faasie** [vinceliuice/Qogir-theme#47]
`Arch Linux`
`Gnome 3.32`

Using Shell `Qogir-gnome-dark` installed via gnome-look.

When logging in, Date and Clock are correct white color. Once clicked on, it turns blue. See image:
![image](https://user-images.githubusercontent.com/4673577/54964163-db2ae200-4f41-11e9-8336-a3f8202da35e.png)

Love the theme! Didn't have this issue prior to upgrade to `3.32`

Thanks!

**Comment by vinceliuice** [comment]
You can delete all old Qogir themes (name changed now) and download the last version of Qogir at github, then reinstall it, because I fixed this issue a few days ago.
