### ISSUE TITLE
Downloaded files name not visable properly (Pantheon desktop)

### ISSUE THREAD

**Issue by subbame** [vinceliuice/Qogir-theme#48]
Downloaded files names are not visible in Google Chrome which shows up at the bottom of the page while and after downloading as shown in the sample screenshot below.

![screenshot_2](https://user-images.githubusercontent.com/14233772/55407001-d1753000-557a-11e9-84bb-18ffdb7873f4.png)

OS: Elementry OS 5

**Comment by vinceliuice** [comment]
Fixed now

**Comment by subbame** [comment]
> Fixed now

Will follow this project closely and probably support you in near future. Since https://www.gnome-look.org/p/1167049/ is dead any alternatives you would recommend for Elementry OS?

**Comment by vinceliuice** [comment]
If you want mac like themes on elementary os then you can use this theme:  https://github.com/vinceliuice/Mojave-gtk-theme  and this one: https://github.com/vinceliuice/Sierra-gtk-theme
