### ISSUE TITLE
XFWM "Win" - Title buttons +1

### ISSUE THREAD

**Issue by Peter-Ries** [vinceliuice/Qogir-theme#49]
While I typed this issue: I read that they aren't available for XFWM.

So I want to vote "+1" for anybody else who'd like to have them ;)

Thanks for your awesome theme!!!

**Comment by vinceliuice** [comment]
No problem， I'll make it support xfwm soon

**Comment by Peter-Ries** [comment]
Happy to see you included sqare buttons for xfwm4. Great, thanks!

**Comment by vinceliuice** [comment]
You are welcome!
