### ISSUE TITLE
Chrome Download status bar text to light on Qogir-(win)-dark

### ISSUE THREAD

**Issue by Peter-Ries** [vinceliuice/Qogir-theme#50]
I use Xubuntu 18.04 with latest Chrome and Qogir-win-dark. Downloading a file showing the dwnload status bar in Chrome: the text ist hard to read:

<a href="http://i.imgur.com/lA7TQGN.png">
  <img src="http://imgur.com/lA7TQGNl.png" />
</a>

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now
