### ISSUE TITLE
Visual Studio Code Pull down menu "light" although dark theme selected

### ISSUE THREAD

**Issue by Peter-Ries** [vinceliuice/Qogir-theme#51]
Hello Vince,

I use XFCE4 with your qogir-dark theme. In Visual Studio code the main menu "File... Edit..." opens with bright background instead of dark background. The VS Code themes only seem to affect the "inside" of the code window, so I suppose it comes from the theme.

Thanks & regards
Peter

<a href="http://i.imgur.com/TH9bNFQ.png">
  <img src="http://imgur.com/TH9bNFQl.png" />
</a>

**Comment by vinceliuice** [comment]
If I set the background dark color it'll make this happen: https://github.com/vinceliuice/vimix-gtk-themes/issues/128 , so I have no choise but make all menu background on Chrome(ium) white, VS code and Atom or all other Chromium based apps will have the same change
