### ISSUE TITLE
Chrome isn't dark anymore (due to fix of issue#50?)

### ISSUE THREAD

**Issue by Peter-Ries** [vinceliuice/Qogir-theme#52]
Hi Vince - me again,

I just wondered: Chrome (73.0.3683.103) isn't dar anymore with Qogir-dark (xfce4).
Active Tab, Bookmarks, Menu all appears to be like in Qogir-light.

See screenshot:
<a href="http://i.imgur.com/nQ9x6fF.png">
  <img src="http://imgur.com/nQ9x6fFl.png" />
</a>

**Comment by vinceliuice** [comment]
Yes, I have no choise, in order to fix #50 and #48 I have to make the font color of chrome black and background white
