### ISSUE TITLE
Draw outlines around menus to improve compatibility with KDE.

### ISSUE THREAD

**Issue by ripefig** [vinceliuice/Qogir-theme#53]
![image](https://user-images.githubusercontent.com/45201036/56090103-1c117900-5ea6-11e9-841a-796e08b71fd7.png)

KDE doesn't support CSD fully, so that's how the menu is drawn. It has no border or shadow. A simple border around menus would fix this.

**Comment by vinceliuice** [comment]
I'll fix this
