### ISSUE TITLE
Create a more neutral variant.

### ISSUE THREAD

**Issue by ripefig** [vinceliuice/Qogir-theme#54]
The current theme may be too bright for some people (me). 

I suggest creating a variant with the following alterations:
* change the main backround to a darker color.
* Change the selection color for buttons to a something more neutral, like 

![image](https://user-images.githubusercontent.com/45201036/56090194-955d9b80-5ea7-11e9-9af8-a3f7dff20f1d.png)

... instead of making it blue. The blue becomes annoying on PDF readers and browsers, as it distracts from the content. A lighter hint would do the job just as well in my opinion.

**Comment by vinceliuice** [comment]
I'll make a Kvantum theme not blue toolbar buttons
