### ISSUE TITLE
Weird shadows arround app switcher

### ISSUE THREAD

**Issue by GitHorsting** [vinceliuice/Qogir-theme#55]
Thanks for maintaining this awesome theme.
There some weird shadows around the alt-tab app switcher. 
I'm on Ubuntu 18.10 using gnome.
![IMG_20190416_125448](https://user-images.githubusercontent.com/49679980/56204346-8281cd00-6047-11e9-97d5-d70f07eb3075.jpg)

**Comment by vinceliuice** [comment]
Fixed now!
