### ISSUE TITLE
Popup menus and modal dialogs not drawing properly on HiDPI (Wayland, fractional scaling)

### ISSUE THREAD

**Issue by alex-spataru** [vinceliuice/Qogir-theme#57]
Hello, 

I am currently running on Ubuntu 19.04 with Wayland at 150% scaling with Wayland. The theme draws perfectly, except on the submenus and modal dialogs on Gnome Shell. Here's a [screenshot](https://pasteboard.co/IbqScqe.png) of the issue.

The issue repeats everywhere where a `border-image` property is set ([example](https://github.com/vinceliuice/Qogir-theme/blob/master/src/gnome-shell/gnome-shell.css#L698)). If I multiply every value by 2 (e.g. changing the line from `border-image: url("assets/menu/menu.svg") 9 9 9 9;` to `border-image: url("assets/menu/menu.svg") 18 18 18 18;`, the popup menus draw correctly, but I don't think that is a good solution. 

Also, many themes present the same issue, I don't know if we should try to fix this manually, or open an issue with the GNOME developers.

Greetings!

**Comment by vinceliuice** [comment]
Thanks, I'll take the temporary solution, I also have no better solutions
