### ISSUE TITLE
Firefox bookmark toolbar separators not visible in folders

### ISSUE THREAD

**Issue by valacar** [vinceliuice/Qogir-theme#58]
If you enable Firefox's bookmark toolbar, add a new folder to it, and then add a few bookmarks to that folder with some separators, the separators won't be visible. Here's what it looks like with the Qogir theme:

![qogir-firefox-separator-bug-after](https://user-images.githubusercontent.com/8539935/56867795-9827b880-699e-11e9-98a8-0fad0822403f.png)

and here's what it should look like (in most other themes, Matcha-Azul in this screenshot):

![qogir-firefox-separator-bug-before](https://user-images.githubusercontent.com/8539935/56867808-dae99080-699e-11e9-928a-cef2876de472.png)

Steps to reproduce:

1. Create new firefox profile (firefox -p from terminal or Alt-F2), and start Firefox
2. Press Alt-v to open View menu, and go to Toolbars>Bookmarks Toolbar and enable it
3. Right-click bookmark toolbar and add New Folder
4. Drag two or more bookmarks into the new folder on the bookmarks toolbar
5. Open the folder and right-click a bookmark (not the top one), and add New Separator

Info about my setup:

* Manjaro (fully updated) with the XFCE desktop environment
* Firefox 66.0.3
* Qogir theme version 2019.04.07.1 (qogir-gtk-theme-git package in AUR)
* 1920x1080 resolution

**Comment by vinceliuice** [comment]
OK, I'll add it back

**Comment by valacar** [comment]
Thanks, I really appreciate the update. It looks like commit f84b5d9f33237e38f753da16e fixed it. 

Excellent theme BTW! Love it! :)

**Comment by vinceliuice** [comment]
You are welcome!
