### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by h0nus** [vinceliuice/Qogir-theme#59]
I can't find anywhere an extension that does the right panel like in this screen :arrow_down:
![img](https://github.com/vinceliuice/Qogir-theme/blob/images/screenshots/screenshot04.png?raw=true)

**Comment by vinceliuice** [comment]
This is Budgie desktop, not a extension of gnome, you can install it from your software manager

**Comment by h0nus** [comment]
Ooooh, i see. It seemed too much gnome. Thanks anyway!

**Comment by vinceliuice** [comment]
You are welcome!
