### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by HabedyOmid** [vinceliuice/Qogir-theme#60]

**Comment by HabedyOmid** [comment]
The package is not available for fedora destro. i tried installing it using yum install gtk-murrine-engine gtk2-engines command.

in result it says: No Package gtk-murrine-engine available

**Comment by vinceliuice** [comment]
Maybe gtk2-engines contains gtk-murrine-engine now, don't worry, if your gtk2 apps like gimp or inkscape works fine then it means murrine engine is installed already
