### ISSUE TITLE
Bug in transparency of workspace switch overlay

### ISSUE THREAD

**Issue by gianpaolom** [vinceliuice/Qogir-theme#62]
As per attached images, there is an issue in the transparency around the workspace switch overlay.
I'm on Ubuntu 19.04/Xorg

![bug-switch](https://user-images.githubusercontent.com/8287946/58111464-672b5400-7be9-11e9-9a0b-00d4a30ff04d.png)

**Comment by vinceliuice** [comment]
I adjusted it, you can download the last one at github

**Comment by gianpaolom** [comment]
Brilliant, thank you!

**Comment by vinceliuice** [comment]
You are welcome!
