### ISSUE TITLE
dark theme does not work in chrome

### ISSUE THREAD

**Issue by mnovozhylov** [vinceliuice/Qogir-theme#68]
Standard gnome-shell dark theme "Yaru" perfectly applies to the chrome. In opposite, using the "Qogir Theme", chrome bars, menu, and popups remain white.

**Comment by Sojiro84** [comment]
My Manjaro Cinnamon, AUR repository also just got updated. I now also have this issue. Chrome is white again, right-click popups are all white. It's terrible.

Currently reverted back through gnome-looks to a version of qogir-dark from januari that works properly. 

I hope this can quickly be fixed.

This a the best theme out there and the white is hurting my eyes during the evening!

**Comment by vinceliuice** [comment]
Fixed now, but on some of web pages, dark menu bg will make it difficult to recognize the black text of popup menus. The early version did not have this issue, so it should be a bug with the last Chrome.
