### ISSUE TITLE
Filezilla looks like windows95

### ISSUE THREAD

**Issue by selwynorren** [vinceliuice/Qogir-theme#7]
Hi,

I must admit this is fast becoming my new favorite theme. Absolutely love it. However some apps are not loving it at all. Filezilla being one of them. When I apply the default Solus adapta theme or even the arc theme, filezilla looks great, but with the Qogir theme it like throwback win95 - lol

**Comment by angela-d** [comment]
This is Filezilla using Qogir-dark on my machine:

![fz](https://user-images.githubusercontent.com/33108490/41553415-610e5974-72f7-11e8-8364-0cec86dcb54e.png)

Did you install the theme to `~/.local`?
If so, see if this helps: https://github.com/vinceliuice/Qogir-theme/issues/6

After you move it, use the Gnome Tweak tool to switch to another theme, then switch back to Qogir-dark to ensure it refreshes completely.

**Comment by selwynorren** [comment]
Hi Spot on there. I did move it and now my filezilla does not look like something from the 90's - Ha ha ha.

Thanks for the great tip
