### ISSUE TITLE
Invalid CSS after "... STRAWBERRY_100". Error when using -i option on master branch.

### ISSUE THREAD

**Issue by aasril** [vinceliuice/Qogir-theme#70]
The exact error message is this, repeated six times:
```
Error: Invalid CSS after "... STRAWBERRY_100": expected 1 selector or at-rule, was "#FF9262;"
        on line 95 of src/_sass/gtk/_colors-public.scss
>> @define-color STRAWBERRY_100 #FF9262;
   --------------^
```

But I don't get the error and nautilus background image is generated just fine with latest release.

OS: Ubuntu 18.04

**Comment by vinceliuice** [comment]
I don't get this issue

**Comment by aasril** [comment]
@vinceliuice I cloned the master branch again and the error still happens.

**Comment by vinceliuice** [comment]
You just run ./install.sh -i and then errors appear?

**Comment by aasril** [comment]
Yes, that's what happened. The themes are still installed but with no background image. Here's screenshot of the error.

![Qogir_i](https://user-images.githubusercontent.com/37625377/60630438-5a269500-9e24-11e9-859a-224c9af8b421.png)

**Comment by vinceliuice** [comment]
I updated, you can download the last one and try again

**Comment by aasril** [comment]
That fixed the error. 

Thanks for this beautfful work!

**Comment by vinceliuice** [comment]
You are welcome
