### ISSUE TITLE
synaptic view bad

### ISSUE THREAD

**Issue by muhaaliss** [vinceliuice/Qogir-theme#75]
Normally this theme looks like google's material theme but synaptic looks like default gnome theme. **I'm using pop!_os**

**Synaptic image with this Qogir theme selected :**

![2019-07-26 19-45-12 ekran görüntüsü](https://user-images.githubusercontent.com/13920155/61967534-44992b00-afde-11e9-9c39-3665fe2bd9f7.png)
![2019-07-26 19-45-23 ekran görüntüsü](https://user-images.githubusercontent.com/13920155/61967537-48c54880-afde-11e9-8981-6b5591e1a339.png)

**Synaptic image with this Arch theme selected :** 

![2019-07-26 19-51-16 ekran görüntüsü](https://user-images.githubusercontent.com/13920155/61967809-06503b80-afdf-11e9-9273-98e3d6d12c34.png)
![2019-07-26 19-51-20 ekran görüntüsü](https://user-images.githubusercontent.com/13920155/61967818-09e3c280-afdf-11e9-8abe-21de22980ae2.png)

**Comment by vinceliuice** [comment]
That's because you install qogir in your user directory not system directory, so root user's software can not use this theme
