### ISSUE TITLE
what desktop environement or extension is used in screenshots 

### ISSUE THREAD

**Issue by tatsujb** [vinceliuice/Qogir-theme#76]
I really like your theme. 

I'm also a real big fan of what ubuntu-gnome has going. to me it kinda "fixed" gnome. but the two main bars thing really feels like wasted screen real estate to me. 

but in your screenshots in your README.md you seem to only have one bar with both the apps and the menus combined.

that's what I want, what is that?

here's some feedback if you're interested: It would be nice to have a version of Qogir where in nautilus, you only have the icon left for the different pinned locations. the text is something we've all memorized by now and is just taking up screen space.

**Comment by vinceliuice** [comment]
This is defualt budgie desktop

**Comment by tatsujb** [comment]
> This is defualt budgie desktop

thanks it seems budgie would be at least some part of it but not the whole thing, this is a side-by side comparison of the screenshot from the readme / Qogir landing page and my own budgie after installing it atop an ubuntu 19.04 : 

![Screenshot from 2019-08-04 07-22-41](https://user-images.githubusercontent.com/5132359/62419894-ae729e00-b68a-11e9-875e-36085bb0d84f.png)

i have gnome-tweaks installed and I look in that and in the settings and there are no options to customize the dock into a taskbar at all, in fact there's a couple missing menu entries from when I log into ubuntu-gnome.

Any idea what I'm missing here?
