### ISSUE TITLE
How to: Sidebar

### ISSUE THREAD

**Issue by netzgestaltung** [vinceliuice/Qogir-theme#87]
Hi there,

this is more a support question:

How is the right hand gnome-shell sidebar in the screenshots sidebar done?

I checked the readme but i think there is no notice on that.
I tried the shell-themes but it stays the normal "gnome-way".

System: Fedora 30, Gnome 3.32.2

Thank you in advance for any hint, keyword or link ;-)

**Comment by vinceliuice** [comment]
It's not gnome-shell desktop, it is budgie desktop. if you like the desktop you can install it.

**Comment by netzgestaltung** [comment]
I have to add that i installed the theme a while ago so maybe i have to update it.

this leads me to the next question ;-)
How to update it? 
Is updating the same as installing?

**Comment by netzgestaltung** [comment]
Ok thank you for the fast answer - i dont think that i change the DE soon.

But i will test it out next time!

**Comment by vinceliuice** [comment]
Just download the last version from github and run ./install.sh
