### ISSUE TITLE
Header bar for Geary 

### ISSUE THREAD

**Issue by jpmgsxr** [vinceliuice/Qogir-theme#89]
Two different shades of blue on the header bar in Geary make it seem off. Checking other GTK themes and the color is consistent across the entirety of the bar. 

![Screenshot from 2019-10-19 22-44-30](https://user-images.githubusercontent.com/808132/67154042-c7badc00-f2c2-11e9-96c3-c03fbbfe3798.png)

Here is an example of it being consistent:

![Screenshot from 2019-10-20 10-17-28](https://user-images.githubusercontent.com/808132/67160943-b950dc80-f323-11e9-8ecc-313a07fe3118.png)

**Comment by vinceliuice** [comment]
Fixed now!
