### ISSUE TITLE
GTK warning Theme parsing error

### ISSUE THREAD

**Issue by Philippe-M** [vinceliuice/Qogir-theme#9]
hello,

I use Qogir-light and when I want to launch the application flameshot I have this message:

`(flameshot:613): Gtk-WARNING **: 09:31:32.950: Theme parsing error: gtk.css:3841:23: Junk at end of value for outline-offset`

the flameshot creator tells me it's a problem with my theme and not the app : https://github.com/lupoDharkael/flameshot/issues/280#issuecomment-407078115

**Comment by vinceliuice** [comment]
Now fixed!
