### ISSUE TITLE
Push Qogir themes to Flathub?

### ISSUE THREAD

**Issue by zeten30** [vinceliuice/Qogir-theme#93]
Hi @vinceliuice ,

I've created Flatpak manifests for Qogir - https://github.com/zeten30/qogir-flatpak

Would you mind if I create a PR for Flathub - https://github.com/flathub/flathub/wiki/App-Submission ? Or you can do it as author.. Any issues?

Thanks in advance

**Comment by vinceliuice** [comment]
Really thanks! I alwalys want someone can help me do this, because I never used flatpak apps before, and I am not familiar with flathub and packaging flatpaks. by the way I made a new release file, maybe you can update the json files before you create a PR for Flathub, Thank you again!

**Comment by zeten30** [comment]
@vinceliuice np. I'll update to new release and create Flathub PR's:)

**Comment by vinceliuice** [comment]
Thanks again！

**Comment by zeten30** [comment]
@vinceliuice - FYI - https://github.com/flathub/flathub/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+qogir

Hope it will be merged. Works fine if I install flatpak themes locally. 

And my flatpak theme manifest generator for reference - https://github.com/zeten30/qogir-flatpak

**Comment by vinceliuice** [comment]
Thank you! I'll add this to README!
