### ISSUE TITLE
Thunar using wrong color in the sidebar.

### ISSUE THREAD

**Issue by Bosmak** [vinceliuice/Qogir-theme#94]
How it used to look:
![thunar_1_6_15](https://user-images.githubusercontent.com/16576236/67627974-9d29cf80-f83c-11e9-81fa-be3365f65f8a.png)

How it looks now:
![thunar_1 8 9](https://user-images.githubusercontent.com/16576236/67627972-9b600c00-f83c-11e9-9151-f61827497dee.png)

The same theme files is being used on both machines, On the one with the most updated version I had tried to install the theme from this git repository on commit `db92456181e43bb4f5d9145fe785e84a6bf5e97a` and had the same issue.

I tried to fix this myself, following the comments [on this topic at xfce forum](https://forum.xfce.org/viewtopic.php?id=11620), couldn't make it work.

Let me known If I can help with anything, If you can point me to here it needs to change I can try from there.

**Comment by vinceliuice** [comment]
I specially do the dark sidebar style

**Comment by vinceliuice** [comment]
If users don't like this style, I can change it back

**Comment by vinceliuice** [comment]
And xfce4 have migrated from gtk2 to gtk3, so the old solution on this forum doesn't work now

**Comment by Bosmak** [comment]
>I specially do the dark sidebar style

I tough this when I used the latest version and had the dark sidebar, then I got the exact same version on the first screenshot and it stills looks different from each other (I zipped the theme folder from there and extracted in the other machine), so I think that something changed on the latest version.

> If users don't like this style, I can change it back

I would like to, but I'm unsure about everyone else, If you prefer I don't care to keep an fork with this change if you can point me what to change.

>And xfce4 have migrated from gtk2 to gtk3, so the old solution on this forum doesn't work now

Oh yeah, I tried the gtk3 fix.
`Imerion` revived this topic asking for gtk3 on post number 7

**Comment by vinceliuice** [comment]
I update it, changed it back

**Comment by Bosmak** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/16576236/67628463-92733880-f844-11e9-8117-195b3e239355.png)

**Comment by vinceliuice** [comment]
That's ok!
